/****************************************************************************
 *                                                                          *
 *  File Name: i2vsdkshmgenerator.h                                         *
 *  Author:                                                                 *
 *      DENSO International America, Inc.                                   *
 *      North America Research Laboratory, California Office                *
 *      3252 Business Park Drive                                            *
 *      Vista, CA 92081                                                     *
 *                                                                          *
 ****************************************************************************/
#include <stdio.h>
#include <string.h>

#undef   int64_t
#include "wsu_sharedmem.h"
#include "wsu_shm.h"
#include "i2v_general.h"
#include "i2v_shm_master.h"

/* autogenerated file */
#include "sdk_types.h"

/* the purpose of this utility is to automatically generate the shared memory
   header file that is supplied with an SDK; because a user may have different
   options that impact the shared memory, a utility needs to exist to create
   the shared memory using what is already compiled into the release i2v */

#define OUTFILE  "rsuSdkShm.h"

#define FILEMACRO "RSUSDKSHM_H"

/* if adding new lines, update index below */
char *copyright[] = {
    "/****************************************************************************\n",
    "*      DENSO International America, Inc.                                   *\n",
    "*      North America Research Laboratory, California Office                *\n",
    "*      3252 Business Park Drive                                            *\n",
    "*      Vista, CA 92081                                                     *\n",
    "****************************************************************************/\n",
    "",   /* DO NOT MOVE - MUST BE LAST */
};
char header[] = "/* WARNING: This file is auto-generated; do not modify unless told to by DENSO */\n";

i2vShmMasterT relshm;
FILE *f;
char wrtBuf[1024] = {0};    /* max legal Linux line size */
char blankline[] = "\n";
int byteswritten;   /* counter to simplify reset of wrtBuf */
int dummy, expectedsize;

/* for now; command line args not accepted; but maybe in the future they will be */
/* JJG: note to self - this is set up to be a horrific violation of common sense - 
   main function may blow up to a few thousand lines in the future; BAD PRACTICE;
   but I'm in a rush now, autogeneration wasn't originally part of the plan */
int main(int argc, char *argv[])
{
    /* before starting anything; verify that SDK definitions are in parity with shm */
    if (sizeof(rsuSPATDataType) != sizeof(i2vSPATDataType)) {
        printf("\nALERT: SDK definitions are out of sync with source code - INSPECT I2V TYPES!!\n");
        return -1;
    }

    /* eliminate any existing file */
    if (NULL == (f=fopen(OUTFILE, "w+"))) {
        printf("\nALERT: SDK file generation failed -- RSU SDK incomplete!!\n");
        return -1;
    }

    /* write copyright and header */
    dummy = 0;
    while (strlen(copyright[dummy])) {
        expectedsize = strlen(copyright[dummy]);
        if (expectedsize != fwrite(copyright[dummy], 1, expectedsize, f)) {
            printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
            fclose(f);
            return -1;
        }
        dummy++;
    }
    /* -1 below to avoid writing NULL byte, file only needs new lines, null byte will add
       garbage characters that makes the file incompatible with compilation */
    fwrite(blankline, 1, sizeof(blankline) - 1, f);   /* don't care if incomplete */
    if (sizeof(header) - 1 != fwrite(header, 1, sizeof(header) - 1, f)) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    fwrite(blankline, 1, sizeof(blankline) - 1, f);   /* don't care if incomplete */

    expectedsize = sprintf(wrtBuf, "#ifndef " FILEMACRO "\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    expectedsize = sprintf(wrtBuf, "#define " FILEMACRO "\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    fwrite(blankline, 1, sizeof(blankline) - 1, f);   /* don't care if incomplete */
    expectedsize = sprintf(wrtBuf, "#include \"sdk_types.h\"\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    fwrite(blankline, 1, sizeof(blankline) - 1, f);   /* don't care if incomplete */
    expectedsize = sprintf(wrtBuf, "#define I2V_SHM_PATH \"" I2V_SHM_PATH "\"\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    fwrite(blankline, 1, sizeof(blankline) - 1, f);   /* don't care if incomplete */
    expectedsize = sprintf(wrtBuf, "typedef enum {\n RSUFALSE = 0,\n RSUTRUE = 1\n} RSUBOOL;\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    fwrite(blankline, 1, sizeof(blankline) - 1, f);   /* don't care if incomplete */
    dummy = sizeof(WSUSPATDataType);
    expectedsize = sprintf(wrtBuf, "typedef union {\n    unsigned char legacySpat[%d];\n    "
        "rsuSPATDataType modernSpat;\n} spatData;\n", dummy);
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    fwrite(blankline, 1, sizeof(blankline) - 1, f);   /* don't care if incomplete */
    expectedsize = sprintf(wrtBuf, "typedef struct {\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);

    /* JJG REMINDER */
    expectedsize = sprintf(wrtBuf, "/* DENSO Engineers: Delete this comment and replace array lengths below with 'S' values "
           "printed \nwhen running I2V from your release that generated this SDK\n"
           "The 'S' values are printed after number of processes loaded and are in sequential order for struct */\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);

    /* !!!!!
       here is where customizations go -- if an SDK requires more than just the contents
       included below from shared memory, add them (or inversely, remove what doesn't belong) 
       remember to only use standard types (i.e. wuint8 = unsigned char, wulong64 = unsigned
       long long); if you aren't sure of the types, look them up -- the exception is WBOOL,
       the RSUBOOL created above is its replacement
       NOTE: if adding new stuff in, update the reserved byte sizes appropriately!!
    */

    /* as of 20180409, all we care about is spat data */
    dummy = ((void *)&relshm.scsSpatData.spatSelector) - ((void *)&relshm);
    expectedsize = sprintf(wrtBuf, "    unsigned char     rsvd1DONOTACCESS[%d];\n", dummy);
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    expectedsize = sprintf(wrtBuf, "    RSUBOOL           spatType;  /* TRUE = modernSpat */\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    expectedsize = sprintf(wrtBuf, "    spatData          liveData;\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    dummy = ((void *)&relshm) - ((void *)&relshm.tim16CfgData); //<= TM !!TODO!! IS this still correct ? spatProcData);
    dummy += sizeof(i2vShmMasterT);
    expectedsize = sprintf(wrtBuf, "    unsigned char     rsvd2DONOTACCESS[%d];\n", dummy);
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);

    /* !!!!!
       ALL customizations to shared memory structure ABOVE -- below closes out the file
    */
    /* close the struct */
    expectedsize = sprintf(wrtBuf, "} __attribute__((packed)) rsuShmMasterT;\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    memset(wrtBuf, 0, expectedsize);
    fwrite(blankline, 1, sizeof(blankline) - 1, f);   /* don't care if incomplete */
    expectedsize = sprintf(wrtBuf, "#endif /* " FILEMACRO " */\n");
    if (expectedsize > (byteswritten = fwrite(wrtBuf, 1, strlen(wrtBuf), f))) {
        /* consider unique alerts for each failure? */
        printf("\nALERT: SDK file generation incomplete -- RSU SDK incomplete!!\n");
        fclose(f);
        return -1;
    }
    fwrite(blankline, 1, sizeof(blankline) - 1, f);   /* don't care if incomplete */

    fclose(f);

    printf("\nCompleted generating SDK files\n");

    return 0;
}
