OSXML_COMMON_RTOBJECTS = \
rtSaxDiag$(OBJ) \
rtSaxErrors$(OBJ) \
rtSaxFindElemID$(OBJ) \
rtSaxFindElemID8$(OBJ) \
rtSaxGetAttributeID$(OBJ) \
rtSaxGetAttrValue$(OBJ) \
rtSaxGetElemID$(OBJ) \
rtSaxGetElemID8$(OBJ) \
rtSaxHasXMLNSAttrs$(OBJ) \
rtSaxIsEmptyBuffer$(OBJ) \
rtSaxLookupElemID$(OBJ) \
rtSaxLookupElemID8$(OBJ) \
rtSaxReportUnexpAttrs$(OBJ) \
rtSaxSetSkipLevelToCurrent$(OBJ) \
rtSaxTestAttributesPresent$(OBJ) \
rtXmlError$(OBJ) \
rtXmlCheckBuffer$(OBJ) \
rtXmlContext$(OBJ) \
rtXmlContextInit$(OBJ) \
rtXmlCmpBase64Str$(OBJ) \
rtXmlCmpHexStr$(OBJ) \
rtXmlCmpQName$(OBJ) \
rtXmlDecBase64Binary$(OBJ) \
rtXmlDecBase64Common$(OBJ) \
rtXmlDecBase64StrValue$(OBJ) \
rtXmlDecBase64Str$(OBJ) \
rtXmlDecBigInt$(OBJ) \
rtXmlDecBool$(OBJ) \
rtXmlDecDateTime$(OBJ) \
rtXmlDecDates$(OBJ) \
rtXmlDecDecimal$(OBJ) \
rtXmlDecDouble$(OBJ) \
rtXmlDecDynBase64Str$(OBJ) \
rtXmlDecDynHexStr$(OBJ) \
rtXmlDecDynUTF8Str$(OBJ) \
rtXmlDecHexBinary$(OBJ) \
rtXmlDecHexStr$(OBJ) \
rtXmlDecHexStrValue$(OBJ) \
rtXmlDecInt$(OBJ) \
rtXmlDecInt64$(OBJ) \
rtXmlDecNSAttr$(OBJ) \
rtXmlDecQName$(OBJ) \
rtXmlDecUInt$(OBJ) \
rtXmlDecUInt64$(OBJ) \
rtXmlDecXSIAttr$(OBJ) \
rtXmlDecXSIAttrs$(OBJ) \
rtXmlEncAny$(OBJ) \
rtXmlEncAnyTypeValue$(OBJ) \
rtXmlEncAttr$(OBJ) \
rtXmlEncAttrC14N$(OBJ) \
rtXmlEncBase64Binary$(OBJ) \
rtXmlEncBase64BinaryAttr$(OBJ) \
rtXmlEncBigInt$(OBJ) \
rtXmlEncBigIntValue$(OBJ) \
rtXmlEncBigIntAttr$(OBJ) \
rtXmlEncBitString$(OBJ) \
rtXmlEncBool$(OBJ) \
rtXmlEncBoolAttr$(OBJ) \
rtXmlEncComment$(OBJ) \
rtXmlEncDates$(OBJ) \
rtXmlEncDatesValue$(OBJ) \
rtXmlEncDateTime$(OBJ) \
rtXmlEncDateTimeValue$(OBJ) \
rtXmlEncDecimal$(OBJ) \
rtXmlEncDecimalValue$(OBJ) \
rtXmlEncDecimalAttr$(OBJ) \
rtXmlEncDecimalPattern$(OBJ) \
rtXmlEncDouble$(OBJ) \
rtXmlEncDoubleAttr$(OBJ) \
rtXmlEncDoublePattern$(OBJ) \
rtXmlEncDoubleValue$(OBJ) \
rtXmlEncEmptyElement$(OBJ) \
rtXmlEncEndDocument$(OBJ) \
rtXmlEncEndElement$(OBJ) \
rtXmlEncFloat$(OBJ) \
rtXmlEncFloatAttr$(OBJ) \
rtXmlEncHexBinary$(OBJ) \
rtXmlEncHexBinaryAttr$(OBJ) \
rtXmlEncIndent$(OBJ) \
rtXmlEncInt$(OBJ) \
rtXmlEncIntAttr$(OBJ) \
rtXmlEncIntPattern$(OBJ) \
rtXmlEncInt64$(OBJ) \
rtXmlEncInt64Attr$(OBJ) \
rtXmlEncInt64Pattern$(OBJ) \
rtXmlEncNamedBits$(OBJ) \
rtXmlEncNSAttrs$(OBJ) \
rtXmlEncReal10$(OBJ) \
rtXmlEncSoapEnvelope$(OBJ) \
rtXmlEncSoapArrayTypeAttr$(OBJ) \
rtXmlEncStartDocument$(OBJ) \
rtXmlEncStartElement$(OBJ) \
rtXmlEncString$(OBJ) \
rtXmlEncUInt$(OBJ) \
rtXmlEncUInt64$(OBJ) \
rtXmlEncUIntAttr$(OBJ) \
rtXmlEncUInt64Attr$(OBJ) \
rtXmlEncUIntPattern$(OBJ) \
rtXmlEncUInt64Pattern$(OBJ) \
rtXmlEncUnicode$(OBJ) \
rtXmlEncXSIAttrs$(OBJ) \
rtXmlEncXSINilAttr$(OBJ) \
rtXmlEncXSITypeAttr$(OBJ) \
rtXmlKeyArray$(OBJ) \
rtXmlMatchHexStr$(OBJ) \
rtXmlMatchBase64Str$(OBJ) \
rtXmlMatchDateTime$(OBJ) \
rtXmlMatchDates$(OBJ) \
rtXmlMemFree$(OBJ) \
rtXmlNamespace$(OBJ) \
rtXmlNewQName$(OBJ) \
rtXmlParseElementName$(OBJ) \
rtXmlParseElemQName$(OBJ) \
rtXmlPrintNSAttrs$(OBJ) \
rtXmlPull$(OBJ) \
rtXmlPutChar$(OBJ) \
rtXmlSetEncBufPtr$(OBJ) \
rtXmlSetEncodingStr$(OBJ) \
rtXmlStrCmpAsc$(OBJ) \
rtXmlStrnCmpAsc$(OBJ) \
rtXmlTreatWhitespaces$(OBJ) \
rtXmlWriteToFile$(OBJ) \
rtXmlWriteUTF16ToFile$(OBJ) \
rtXmlpCreateReader$(OBJ) \
rtXmlpDecAny$(OBJ) \
rtXmlpDecAnyElem$(OBJ) \
rtXmlpDecAnyAttrStr$(OBJ) \
rtXmlpDecBase64Str$(OBJ) \
rtXmlpDecBigInt$(OBJ) \
rtXmlpDecBitString$(OBJ) \
rtXmlpDecBool$(OBJ) \
rtXmlpDecDateTime$(OBJ) \
rtXmlpDecDecimal$(OBJ) \
rtXmlpDecDouble$(OBJ) \
rtXmlpDecDynBase64Str$(OBJ) \
rtXmlpDecDynHexStr$(OBJ) \
rtXmlpDecHexStr$(OBJ) \
rtXmlpDecInt$(OBJ) \
rtXmlpDecInt64$(OBJ) \
rtXmlpDecNamedBits$(OBJ) \
rtXmlpDecStrList$(OBJ) \
rtXmlpDecUInt$(OBJ) \
rtXmlpDecUInt64$(OBJ) \
rtXmlpDecUnicode$(OBJ) \
rtXmlpDecXmlStr$(OBJ) \
rtXmlpDecXSIAttr$(OBJ) \
rtXmlpDecXSITypeAttr$(OBJ) \
rtXmlpEvent$(OBJ) \
rtXmlpGetAttributeCount$(OBJ) \
rtXmlpGetAttributeID$(OBJ) \
rtXmlpGetContent$(OBJ) \
rtXmlpGetNextElem$(OBJ) \
rtXmlpGetNextElemID$(OBJ) \
rtXmlpHasAttributes$(OBJ) \
rtXmlpIsInGroup$(OBJ) \
rtXmlpIsUTF8Encoding$(OBJ) \
rtXmlpMatch$(OBJ) \
rtXmlpReadBytes$(OBJ) \
rtXmlpSelectAttribute$(OBJ) \
rtXmlWriteChars$(OBJ)

OSXML_C_RTOBJECTS = \
$(OSXML_COMMON_RTOBJECTS) \
rtSaxCAny$(OBJ) \
rtSaxCAnyType$(OBJ) \
rtSaxCSimpleType$(OBJ) \
rtSaxCSoap$(OBJ) \
rtSaxCStrList$(OBJ) \
rtSaxCXmlHandler$(OBJ) \
rtSaxCXmlStreamHandler$(OBJ) \
rtSaxSortAttrs$(OBJ) \
rtXmlEncAnyAttr$(OBJ)

OSXML_CPP_RTOBJECTS = \
$(OSXML_C_RTOBJECTS) \
rtSaxCppParser$(OBJ) \
rtSaxCppSimpleType$(OBJ) \
OSXMLMessageBuffer$(OBJ) \
OSXMLEncodeBuffer$(OBJ) \
OSXMLEncodeStream$(OBJ) \
OSXMLDecodeBuffer$(OBJ) 

LIBXML2EXT_OBJECTS = \
rtLx2DomSerializeToMem$(OBJ)
