/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.2.4, Date: 06-Mar-2019.
 */
#include "AddGrpB.h"
#include "rtsrc/rtPrintToStream.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtxsrc/rtxCommon.h"

int asn1PrtToStrm_AddGrpB_Angle (OSCTXT *pctxt, 
   const char* name, const AddGrpB_Angle* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_Day (OSCTXT *pctxt, const char* name, const Day* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_DayOfWeek (OSCTXT *pctxt, 
   const char* name, const DayOfWeek* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtxPrintToStream (pctxt, name);
   switch (*pvalue) {
      case 0:
         rtxPrintToStream (pctxt, " = unknown\n");
         break;
      case 1:
         rtxPrintToStream (pctxt, " = monday\n");
         break;
      case 2:
         rtxPrintToStream (pctxt, " = tuesday\n");
         break;
      case 3:
         rtxPrintToStream (pctxt, " = wednesday\n");
         break;
      case 4:
         rtxPrintToStream (pctxt, " = thursday\n");
         break;
      case 5:
         rtxPrintToStream (pctxt, " = friday\n");
         break;
      case 6:
         rtxPrintToStream (pctxt, " = saturday\n");
         break;
      case 7:
         rtxPrintToStream (pctxt, " = sunday\n");
         break;
      default:
         rtxPrintToStream (pctxt," = ???\n");
   }

   return 0;
}

int asn1PrtToStrm_DegreesLat (OSCTXT *pctxt, 
   const char* name, const DegreesLat* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamInteger (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_DegreesLong (OSCTXT *pctxt, 
   const char* name, const DegreesLong* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamInteger (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_AddGrpB_Elevation (OSCTXT *pctxt, 
   const char* name, const AddGrpB_Elevation* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamInteger (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_Holiday (OSCTXT *pctxt, 
   const char* name, const Holiday* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtxPrintToStream (pctxt, name);
   switch (*pvalue) {
      case 0:
         rtxPrintToStream (pctxt, " = weekday\n");
         break;
      case 1:
         rtxPrintToStream (pctxt, " = holiday\n");
         break;
      default:
         rtxPrintToStream (pctxt," = ???\n");
   }

   return 0;
}

int asn1PrtToStrm_Hour (OSCTXT *pctxt, const char* name, const Hour* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_LatitudeDMS (OSCTXT *pctxt, 
   const char* name, const LatitudeDMS* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamInteger (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_LongitudeDMS (OSCTXT *pctxt, 
   const char* name, const LongitudeDMS* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamInteger (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_MaxTimetoChange (OSCTXT *pctxt, 
   const char* name, const MaxTimetoChange* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_MinTimetoChange (OSCTXT *pctxt, 
   const char* name, const MinTimetoChange* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_Minute (OSCTXT *pctxt, 
   const char* name, const Minute* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_MinutesAngle (OSCTXT *pctxt, 
   const char* name, const MinutesAngle* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_Month (OSCTXT *pctxt, const char* name, const Month* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_AddGrpB_MsgCount (OSCTXT *pctxt, 
   const char* name, const AddGrpB_MsgCount* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_Second (OSCTXT *pctxt, 
   const char* name, const Second* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_SecondsAngle (OSCTXT *pctxt, 
   const char* name, const SecondsAngle* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_SummerTime (OSCTXT *pctxt, 
   const char* name, const SummerTime* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtxPrintToStream (pctxt, name);
   switch (*pvalue) {
      case 0:
         rtxPrintToStream (pctxt, " = notInSummerTime\n");
         break;
      case 1:
         rtxPrintToStream (pctxt, " = inSummerTime\n");
         break;
      default:
         rtxPrintToStream (pctxt," = ???\n");
   }

   return 0;
}

int asn1PrtToStrm_TenthSecond (OSCTXT *pctxt, 
   const char* name, const TenthSecond* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_TimeRemaining (OSCTXT *pctxt, 
   const char* name, const TimeRemaining* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_Year (OSCTXT *pctxt, const char* name, const Year* pvalue)
{
   rtPrintToStreamIndent (pctxt);
   rtPrintToStreamUnsigned (pctxt, name, *pvalue);
   return 0;
}

int asn1PrtToStrm_LatitudeDMS2 (OSCTXT *pctxt, 
   const char* name, const LatitudeDMS2* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_DegreesLat (pctxt, "d", &pvalue->d);

   asn1PrtToStrm_MinutesAngle (pctxt, "m_", &pvalue->m_);

   asn1PrtToStrm_SecondsAngle (pctxt, "s", &pvalue->s);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_LongitudeDMS2 (OSCTXT *pctxt, 
   const char* name, const LongitudeDMS2* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_DegreesLong (pctxt, "d", &pvalue->d);

   asn1PrtToStrm_MinutesAngle (pctxt, "m_", &pvalue->m_);

   asn1PrtToStrm_SecondsAngle (pctxt, "s", &pvalue->s);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_Node_LLdms_48b (OSCTXT *pctxt, 
   const char* name, const Node_LLdms_48b* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_LongitudeDMS (pctxt, "lon", &pvalue->lon);

   asn1PrtToStrm_LatitudeDMS (pctxt, "lat", &pvalue->lat);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_Node_LLdms_80b (OSCTXT *pctxt, 
   const char* name, const Node_LLdms_80b* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_LongitudeDMS2 (pctxt, "lon", &pvalue->lon);

   asn1PrtToStrm_LatitudeDMS2 (pctxt, "lat", &pvalue->lat);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_LaneDataAttribute_addGrpB (OSCTXT *pctxt, 
   const char* name, const LaneDataAttribute_addGrpB* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   rtPrintToStreamOpenTypeExtBraceText (pctxt, "extElem1", &pvalue->extElem1);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_MovementEvent_addGrpB (OSCTXT *pctxt, 
   const char* name, const MovementEvent_addGrpB* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   if (pvalue->m.startTimePresent) {
      asn1PrtToStrm_TimeRemaining (pctxt, "startTime", &pvalue->startTime);
   }

   asn1PrtToStrm_MinTimetoChange (pctxt, "minEndTime", &pvalue->minEndTime);

   if (pvalue->m.maxEndTimePresent) {
      asn1PrtToStrm_MaxTimetoChange (pctxt, "maxEndTime", &pvalue->maxEndTime);
   }

   if (pvalue->m.likelyTimePresent) {
      asn1PrtToStrm_TimeRemaining (pctxt, "likelyTime", &pvalue->likelyTime);
   }

   if (pvalue->m.confidencePresent) {
      asn1PrtToStrm_TimeIntervalConfidence (pctxt, "confidence", &pvalue->confidence);
   }

   if (pvalue->m.nextTimePresent) {
      asn1PrtToStrm_TimeRemaining (pctxt, "nextTime", &pvalue->nextTime);
   }

   rtPrintToStreamOpenTypeExtBraceText (pctxt, "extElem1", &pvalue->extElem1);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_NodeOffsetPointXY_addGrpB (OSCTXT *pctxt, 
   const char* name, const NodeOffsetPointXY_addGrpB* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   switch (pvalue->t)
   {
      /* posA */
      case 1:
      {
         asn1PrtToStrm_Node_LLdms_48b (pctxt, "posA", pvalue->u.posA);
         break;
      }
      /* posB */
      case 2:
      {
         asn1PrtToStrm_Node_LLdms_80b (pctxt, "posB", pvalue->u.posB);
         break;
      }
      /* extElem1 */
      case 3:
      {
         rtPrintToStreamIndent (pctxt);
         rtPrintToStreamHexStr (pctxt, "extElem1",
            pvalue->u.extElem1->numocts, pvalue->u.extElem1->data);
         break;
      }
      default:;
   }

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_Position3D_addGrpB (OSCTXT *pctxt, 
   const char* name, const Position3D_addGrpB* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_LatitudeDMS2 (pctxt, "latitude", &pvalue->latitude);

   asn1PrtToStrm_LongitudeDMS2 (pctxt, "longitude", &pvalue->longitude);

   asn1PrtToStrm_AddGrpB_Elevation (pctxt, "elevation", &pvalue->elevation);

   rtPrintToStreamOpenTypeExtBraceText (pctxt, "extElem1", &pvalue->extElem1);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

int asn1PrtToStrm_AddGrpB_TimeMark (OSCTXT *pctxt, 
   const char* name, const AddGrpB_TimeMark* pvalue)
{
   rtPrintToStreamOpenBrace (pctxt, name);

   asn1PrtToStrm_Year (pctxt, "year", &pvalue->year);

   asn1PrtToStrm_Month (pctxt, "month", &pvalue->month);

   asn1PrtToStrm_Day (pctxt, "day", &pvalue->day);

   asn1PrtToStrm_SummerTime (pctxt, "summerTime", &pvalue->summerTime);

   asn1PrtToStrm_Holiday (pctxt, "holiday", &pvalue->holiday);

   asn1PrtToStrm_DayOfWeek (pctxt, "dayofWeek", &pvalue->dayofWeek);

   asn1PrtToStrm_Hour (pctxt, "hour", &pvalue->hour);

   asn1PrtToStrm_Minute (pctxt, "minute", &pvalue->minute);

   asn1PrtToStrm_Second (pctxt, "second", &pvalue->second);

   asn1PrtToStrm_TenthSecond (pctxt, "tenthSecond", &pvalue->tenthSecond);

   rtPrintToStreamCloseBrace (pctxt);
   return 0;
}

