/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.2.4, Date: 06-Mar-2019.
 */
#include "ITIS.h"
#include "rtxsrc/rtxCommon.h"

EXTERN int asn1PD_ITIScodes (OSCTXT* pctxt, ITIScodes* pvalue)
{
   if (pctxt->buffer.aligned) {
      int stat2 = PD_BYTE_ALIGN (pctxt);
      if (stat2 != 0) return LOG_RTERR (pctxt, stat2);
   }
   return rtxDecBitsToUInt16 (pctxt, pvalue, pctxt->buffer.aligned ? 16 : 16);
}

EXTERN int asn1PD_VehicleGroupAffected (OSCTXT* pctxt, VehicleGroupAffected* pvalue)
{
   int stat = 0;
   OSUINT32 ui;
   OSBOOL extbit = FALSE;

   RTDIAGSTRM2 (pctxt,"asn1PD_VehicleGroupAffected: start\n");

   /* extension bit */

   PU_NEWFIELD (pctxt, "extension marker");

   stat = DEC_BIT (pctxt, &extbit);
   if (stat != 0) return stat;

   PU_SETBITCOUNT (pctxt);

   if (extbit) {
      PU_NEWFIELD (pctxt, "extension value");

      stat = pd_SmallNonNegWholeNumber (pctxt, &ui);
      if (stat != 0) return stat;

      PU_SETBITCOUNT (pctxt);

      *pvalue = 0x7fffffff;
   }
   else {
      stat = pd_ConsUnsigned (pctxt, pvalue, 0, OSUINTCONST(34));
      if (stat != 0) return stat;
      *pvalue += 9217;
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_VehicleGroupAffected: end\n");

   return (stat);
}

EXTERN int asn1PD_IncidentResponseEquipment (OSCTXT* pctxt, IncidentResponseEquipment* pvalue)
{
   int stat = 0;
   OSUINT32 ui;
   OSBOOL extbit = FALSE;

   RTDIAGSTRM2 (pctxt,"asn1PD_IncidentResponseEquipment: start\n");

   /* extension bit */

   PU_NEWFIELD (pctxt, "extension marker");

   stat = DEC_BIT (pctxt, &extbit);
   if (stat != 0) return stat;

   PU_SETBITCOUNT (pctxt);

   if (extbit) {
      PU_NEWFIELD (pctxt, "extension value");

      stat = pd_SmallNonNegWholeNumber (pctxt, &ui);
      if (stat != 0) return stat;

      PU_SETBITCOUNT (pctxt);

      *pvalue = 0x7fffffff;
   }
   else {
      stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(71));
      if (stat != 0) return stat;

      switch (ui) {
         case 0: *pvalue = ground_fire_suppression; break;
         case 1: *pvalue = heavy_ground_equipment; break;
         case 2: *pvalue = aircraft; break;
         case 3: *pvalue = marine_equipment; break;
         case 4: *pvalue = support_equipment; break;
         case 5: *pvalue = medical_rescue_unit; break;
         case 6: *pvalue = other_1; break;
         case 7: *pvalue = ground_fire_suppression_other; break;
         case 8: *pvalue = engine; break;
         case 9: *pvalue = truck_or_aerial; break;
         case 10: *pvalue = quint; break;
         case 11: *pvalue = tanker_pumper_combination; break;
         case 12: *pvalue = brush_truck; break;
         case 13: *pvalue = aircraft_rescue_firefighting; break;
         case 14: *pvalue = heavy_ground_equipment_other; break;
         case 15: *pvalue = dozer_or_plow; break;
         case 16: *pvalue = tractor; break;
         case 17: *pvalue = tanker_or_tender; break;
         case 18: *pvalue = aircraft_other; break;
         case 19: *pvalue = aircraft_fixed_wing_tanker; break;
         case 20: *pvalue = helitanker; break;
         case 21: *pvalue = helicopter; break;
         case 22: *pvalue = marine_equipment_other; break;
         case 23: *pvalue = fire_boat_with_pump; break;
         case 24: *pvalue = boat_no_pump; break;
         case 25: *pvalue = support_apparatus_other; break;
         case 26: *pvalue = breathing_apparatus_support; break;
         case 27: *pvalue = light_and_air_unit; break;
         case 28: *pvalue = medical_rescue_unit_other; break;
         case 29: *pvalue = rescue_unit; break;
         case 30: *pvalue = urban_search_rescue_unit; break;
         case 31: *pvalue = high_angle_rescue; break;
         case 32: *pvalue = crash_fire_rescue; break;
         case 33: *pvalue = bLS_unit; break;
         case 34: *pvalue = aLS_unit; break;
         case 35: *pvalue = mobile_command_post; break;
         case 36: *pvalue = chief_officer_car; break;
         case 37: *pvalue = hAZMAT_unit; break;
         case 38: *pvalue = type_i_hand_crew; break;
         case 39: *pvalue = type_ii_hand_crew; break;
         case 40: *pvalue = privately_owned_vehicle; break;
         case 41: *pvalue = other_apparatus_resource; break;
         case 42: *pvalue = ambulance_1; break;
         case 43: *pvalue = bomb_squad_van; break;
         case 44: *pvalue = combine_harvester; break;
         case 45: *pvalue = construction_vehicle; break;
         case 46: *pvalue = farm_tractor; break;
         case 47: *pvalue = grass_cutting_machines; break;
         case 48: *pvalue = hAZMAT_containment_tow; break;
         case 49: *pvalue = heavy_tow; break;
         case 50: *pvalue = hedge_cutting_machines; break;
         case 51: *pvalue = light_tow; break;
         case 52: *pvalue = mobile_crane; break;
         case 53: *pvalue = refuse_collection_vehicle; break;
         case 54: *pvalue = resurfacing_vehicle; break;
         case 55: *pvalue = road_sweeper; break;
         case 56: *pvalue = roadside_litter_collection_crews; break;
         case 57: *pvalue = salvage_vehicle; break;
         case 58: *pvalue = sand_truck; break;
         case 59: *pvalue = snowplow; break;
         case 60: *pvalue = steam_roller; break;
         case 61: *pvalue = swat_team_van; break;
         case 62: *pvalue = track_laying_vehicle; break;
         case 63: *pvalue = unknown_vehicle; break;
         case 64: *pvalue = white_lining_vehicle; break;
         case 65: *pvalue = dump_truck; break;
         case 66: *pvalue = supervisor_vehicle; break;
         case 67: *pvalue = snow_blower; break;
         case 68: *pvalue = rotary_snow_blower; break;
         case 69: *pvalue = road_grader; break;
         case 70: *pvalue = steam_truck; break;
         case 71: *pvalue = flatbed_tow; break;
         default: return RTERR_INVENUM;
      }
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_IncidentResponseEquipment: end\n");

   return (stat);
}

EXTERN int asn1PD_ResponderGroupAffected (OSCTXT* pctxt, ResponderGroupAffected* pvalue)
{
   int stat = 0;
   OSUINT32 ui;
   OSBOOL extbit = FALSE;

   RTDIAGSTRM2 (pctxt,"asn1PD_ResponderGroupAffected: start\n");

   /* extension bit */

   PU_NEWFIELD (pctxt, "extension marker");

   stat = DEC_BIT (pctxt, &extbit);
   if (stat != 0) return stat;

   PU_SETBITCOUNT (pctxt);

   if (extbit) {
      PU_NEWFIELD (pctxt, "extension value");

      stat = pd_SmallNonNegWholeNumber (pctxt, &ui);
      if (stat != 0) return stat;

      PU_SETBITCOUNT (pctxt);

      *pvalue = 0x7fffffff;
   }
   else {
      stat = pd_ConsUnsigned (pctxt, pvalue, 0, OSUINTCONST(13));
      if (stat != 0) return stat;
      *pvalue += 9729;
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_ResponderGroupAffected: end\n");

   return (stat);
}

EXTERN int asn1PD_ITIStext (OSCTXT* pctxt, ITIStext* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ITIStext: start\n");

   PU_SETSIZECONSTRAINT (pctxt, OSUINTCONST(1), OSUINTCONST(500), 0, 0);

   stat = pd_ConstrainedStringEx (pctxt, pvalue, 0, 8, 7, 7);
   if (stat != 0) return stat;

   RTDIAGSTRM2 (pctxt,"asn1PD_ITIStext: end\n");

   return (stat);
}

EXTERN int asn1PD_ITIScodesAndText_element_item (OSCTXT* pctxt, ITIScodesAndText_element_item* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt,"asn1PD_ITIScodesAndText_element_item: start\n");

   RTXCTXTPUSHELEMNAME (pctxt, "t");

   {
      OSBOOL b = 0;
      DEC_BIT (pctxt, &b);
      ui = b;
   }
   pvalue->t = ui + 1;

   RTXCTXTPOPELEMNAME (pctxt);

   switch (ui) {
      /* itis */
      case 0:
         stat = asn1PD_ITIScodes (pctxt, &pvalue->u.itis);
         if (stat != 0) return stat;

         break;

      /* text */
      case 1:
         stat = asn1PD_ITIStext (pctxt, &pvalue->u.text);
         if (stat != 0) return stat;

         break;

      default:
         return RTERR_INVOPT;
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_ITIScodesAndText_element_item: end\n");

   return (stat);
}

EXTERN int asn1PD_ITIScodesAndText_element (OSCTXT* pctxt, ITIScodesAndText_element* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ITIScodesAndText_element: start\n");

   /* decode root elements */
   /* decode item */
   stat = asn1PD_ITIScodesAndText_element_item (pctxt, &pvalue->item);
   if (stat != 0) return stat;

   RTDIAGSTRM2 (pctxt,"asn1PD_ITIScodesAndText_element: end\n");

   return (stat);
}

EXTERN int asn1PD_ITIScodesAndText (OSCTXT* pctxt, ITIScodesAndText* pvalue)
{
   int stat = 0;
   OSRTDListNode* pnode;
   OSSIZE count = 0;
   OSSIZE xx1 = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ITIScodesAndText: start\n");

   /* decode length determinant */

   PU_SETSIZECONSTRAINT (pctxt, OSUINTCONST(1), OSUINTCONST(100), 0, 0);

   stat = pd_Length64 (pctxt, &count);
   if (stat != 0) return stat;

   /* decode elements */

   rtxDListInit (pvalue);

   for (xx1 = 0; xx1 < count; xx1++) {
      ITIScodesAndText_element* pdata;
      rtxDListAllocNodeAndData (pctxt, ITIScodesAndText_element, &pnode, &pdata);

      if (pnode == NULL)
         return RTERR_NOMEM;

      asn1Init_ITIScodesAndText_element (pdata);

      rtxDListAppendNode (pvalue, pnode);
      stat = asn1PD_ITIScodesAndText_element (pctxt, pdata);
      if (stat != 0) return stat;

   }

   RTDIAGSTRM2 (pctxt,"asn1PD_ITIScodesAndText: end\n");

   return (stat);
}

EXTERN int asn1PD_GenericLocations (OSCTXT* pctxt, GenericLocations* pvalue)
{
   int stat = 0;
   OSUINT32 ui;
   OSBOOL extbit = FALSE;

   RTDIAGSTRM2 (pctxt,"asn1PD_GenericLocations: start\n");

   /* extension bit */

   PU_NEWFIELD (pctxt, "extension marker");

   stat = DEC_BIT (pctxt, &extbit);
   if (stat != 0) return stat;

   PU_SETBITCOUNT (pctxt);

   if (extbit) {
      PU_NEWFIELD (pctxt, "extension value");

      stat = pd_SmallNonNegWholeNumber (pctxt, &ui);
      if (stat != 0) return stat;

      PU_SETBITCOUNT (pctxt);

      *pvalue = 0x7fffffff;
   }
   else {
      stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(95));
      if (stat != 0) return stat;

      switch (ui) {
         case 0: *pvalue = on_bridges; break;
         case 1: *pvalue = in_tunnels; break;
         case 2: *pvalue = entering_or_leaving_tunnels; break;
         case 3: *pvalue = on_ramps; break;
         case 4: *pvalue = in_road_construction_area; break;
         case 5: *pvalue = around_a_curve; break;
         case 6: *pvalue = on_minor_roads; break;
         case 7: *pvalue = in_the_opposing_lanes; break;
         case 8: *pvalue = adjacent_to_roadway; break;
         case 9: *pvalue = on_bend; break;
         case 10: *pvalue = entire_intersection; break;
         case 11: *pvalue = in_the_median; break;
         case 12: *pvalue = moved_to_side_of_road; break;
         case 13: *pvalue = moved_to_shoulder; break;
         case 14: *pvalue = on_the_roadway; break;
         case 15: *pvalue = in_shaded_areas; break;
         case 16: *pvalue = in_low_lying_areas; break;
         case 17: *pvalue = in_the_downtown_area; break;
         case 18: *pvalue = in_the_inner_city_area; break;
         case 19: *pvalue = in_parts; break;
         case 20: *pvalue = in_some_places; break;
         case 21: *pvalue = in_the_ditch; break;
         case 22: *pvalue = in_the_valley; break;
         case 23: *pvalue = on_hill_top; break;
         case 24: *pvalue = near_the_foothills; break;
         case 25: *pvalue = at_high_altitudes; break;
         case 26: *pvalue = near_the_lake; break;
         case 27: *pvalue = near_the_shore; break;
         case 28: *pvalue = over_the_crest_of_a_hill; break;
         case 29: *pvalue = other_than_on_the_roadway; break;
         case 30: *pvalue = near_the_beach; break;
         case 31: *pvalue = near_beach_access_point; break;
         case 32: *pvalue = lower_level; break;
         case 33: *pvalue = upper_level; break;
         case 34: *pvalue = airport; break;
         case 35: *pvalue = concourse; break;
         case 36: *pvalue = gate; break;
         case 37: *pvalue = baggage_claim; break;
         case 38: *pvalue = customs_point; break;
         case 39: *pvalue = station; break;
         case 40: *pvalue = platform; break;
         case 41: *pvalue = dock; break;
         case 42: *pvalue = depot; break;
         case 43: *pvalue = ev_charging_point; break;
         case 44: *pvalue = information_welcome_point; break;
         case 45: *pvalue = at_rest_area; break;
         case 46: *pvalue = at_service_area; break;
         case 47: *pvalue = at_weigh_station; break;
         case 48: *pvalue = picnic_areas; break;
         case 49: *pvalue = rest_area; break;
         case 50: *pvalue = service_stations; break;
         case 51: *pvalue = toilets; break;
         case 52: *pvalue = on_the_right; break;
         case 53: *pvalue = on_the_left; break;
         case 54: *pvalue = in_the_center; break;
         case 55: *pvalue = in_the_opposite_direction; break;
         case 56: *pvalue = cross_traffic; break;
         case 57: *pvalue = northbound_traffic; break;
         case 58: *pvalue = eastbound_traffic; break;
         case 59: *pvalue = southbound_traffic; break;
         case 60: *pvalue = westbound_traffic; break;
         case 61: *pvalue = north; break;
         case 62: *pvalue = south; break;
         case 63: *pvalue = east; break;
         case 64: *pvalue = west; break;
         case 65: *pvalue = northeast; break;
         case 66: *pvalue = northwest; break;
         case 67: *pvalue = southeast; break;
         case 68: *pvalue = southwest; break;
         case 69: *pvalue = mountain_pass; break;
         case 70: *pvalue = reservation_center; break;
         case 71: *pvalue = nearby_basin; break;
         case 72: *pvalue = on_tracks; break;
         case 73: *pvalue = dip; break;
         case 74: *pvalue = traffic_circle; break;
         case 75: *pvalue = park_and_ride_lot; break;
         case 76: *pvalue = to; break;
         case 77: *pvalue = by; break;
         case 78: *pvalue = through; break;
         case 79: *pvalue = area_of; break;
         case 80: *pvalue = under; break;
         case 81: *pvalue = over; break;
         case 82: *pvalue = from; break;
         case 83: *pvalue = approaching; break;
         case 84: *pvalue = entering_at; break;
         case 85: *pvalue = exiting_at; break;
         case 86: *pvalue = across_tracks; break;
         case 87: *pvalue = in_street; break;
         case 88: *pvalue = on_curve; break;
         case 89: *pvalue = shoulder; break;
         case 90: *pvalue = crossover; break;
         case 91: *pvalue = cross_road; break;
         case 92: *pvalue = side_road; break;
         case 93: *pvalue = bus_stop; break;
         case 94: *pvalue = intersection; break;
         case 95: *pvalue = roadside_park; break;
         default: return RTERR_INVENUM;
      }
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_GenericLocations: end\n");

   return (stat);
}

