BER_C_OBJECTS_NLC = \
   $(OBJDIR)$(PS)berConvertDefIndef$(OBJ) \
   $(OBJDIR)$(PS)berError$(OBJ) \
   $(OBJDIR)$(PS)berGetLibInfo$(OBJ) \
   $(OBJDIR)$(PS)berParseTagLen$(OBJ) \
   $(OBJDIR)$(PS)berTagToString$(OBJ) \
   $(OBJDIR)$(PS)xd_real$(OBJ) \
   $(OBJDIR)$(PS)xd_indeflen$(OBJ) \
   $(OBJDIR)$(PS)xd_enum$(OBJ) \
   $(OBJDIR)$(PS)xd_count$(OBJ) \
   $(OBJDIR)$(PS)xd_common$(OBJ) \
   $(OBJDIR)$(PS)xd_match$(OBJ) \
   $(OBJDIR)$(PS)xd_match1$(OBJ) \
   $(OBJDIR)$(PS)xd_chkend$(OBJ) \
   $(OBJDIR)$(PS)xd_bcdstr$(OBJ) \
   $(OBJDIR)$(PS)xd_16BitCharStr$(OBJ) \
   $(OBJDIR)$(PS)xd_32BitCharStr$(OBJ) \
   $(OBJDIR)$(PS)xd_OpenTypeExt$(OBJ) \
   $(OBJDIR)$(PS)xd_OpenTypeAppend$(OBJ) \
   $(OBJDIR)$(PS)xd_octstr_s$(OBJ) \
   $(OBJDIR)$(PS)xd_oid64$(OBJ) \
   $(OBJDIR)$(PS)xd_reloid$(OBJ) \
   $(OBJDIR)$(PS)xd_null$(OBJ) \
   $(OBJDIR)$(PS)xd_NextElement$(OBJ) \
   $(OBJDIR)$(PS)xd_MovePastEOC$(OBJ) \
   $(OBJDIR)$(PS)xd_memcpy$(OBJ) \
   $(OBJDIR)$(PS)xd_len$(OBJ) \
   $(OBJDIR)$(PS)xd_int16$(OBJ) \
   $(OBJDIR)$(PS)xd_int64$(OBJ) \
   $(OBJDIR)$(PS)xd_uint64$(OBJ) \
   $(OBJDIR)$(PS)xd_setp$(OBJ) \
   $(OBJDIR)$(PS)xd_Tag1AndLen$(OBJ) \
   $(OBJDIR)$(PS)xd_consstr$(OBJ) \
   $(OBJDIR)$(PS)xdf_TagAndLen$(OBJ) \
   $(OBJDIR)$(PS)xdf_ReadContents$(OBJ) \
   $(OBJDIR)$(PS)xe_real$(OBJ) \
   $(OBJDIR)$(PS)xe_cer16BitCharStr$(OBJ) \
   $(OBJDIR)$(PS)xe_cer32BitCharStr$(OBJ) \
   $(OBJDIR)$(PS)xe_cerbitstr$(OBJ) \
   $(OBJDIR)$(PS)xe_cercharstr$(OBJ) \
   $(OBJDIR)$(PS)xe_ceroctstr$(OBJ) \
   $(OBJDIR)$(PS)xe_common$(OBJ) \
   $(OBJDIR)$(PS)xe_charstr$(OBJ) \
   $(OBJDIR)$(PS)xe_datestr$(OBJ) \
   $(OBJDIR)$(PS)xe_timestr$(OBJ) \
   $(OBJDIR)$(PS)xe_datetimestr$(OBJ) \
   $(OBJDIR)$(PS)xe_timeofdaystr$(OBJ) \
   $(OBJDIR)$(PS)xe_durationstr$(OBJ) \
   $(OBJDIR)$(PS)xe_bcdstr$(OBJ) \
   $(OBJDIR)$(PS)xe_16BitCharStr$(OBJ) \
   $(OBJDIR)$(PS)xe_32BitCharStr$(OBJ) \
   $(OBJDIR)$(PS)xe_TagAndIndefLen$(OBJ) \
   $(OBJDIR)$(PS)xe_OpenType$(OBJ) \
   $(OBJDIR)$(PS)xe_OpenTypeExt$(OBJ) \
   $(OBJDIR)$(PS)xe_oid64$(OBJ) \
   $(OBJDIR)$(PS)xe_reloid$(OBJ) \
   $(OBJDIR)$(PS)xe_null$(OBJ) \
   $(OBJDIR)$(PS)xe_memcpy$(OBJ) \
   $(OBJDIR)$(PS)xe_int16$(OBJ) \
   $(OBJDIR)$(PS)xe_int64$(OBJ) \
   $(OBJDIR)$(PS)xe_uint64$(OBJ) \
   $(OBJDIR)$(PS)xe_enum$(OBJ) \
   $(OBJDIR)$(PS)xe_ptr$(OBJ) \
   $(OBJDIR)$(PS)xe_free$(OBJ) \
   $(OBJDIR)$(PS)xu_BufferState$(OBJ) \
   $(OBJDIR)$(PS)xu_dump2$(OBJ) \
   $(OBJDIR)$(PS)xu_fdump$(OBJ) \
   $(OBJDIR)$(PS)xu_fmt_tag$(OBJ) \
   $(OBJDIR)$(PS)xu_fmt_contents$(OBJ) \
   $(OBJDIR)$(PS)berDecDecimal$(OBJ) \
   $(OBJDIR)$(PS)berDecReal10$(OBJ) \
   $(OBJDIR)$(PS)berEncReal10$(OBJ) \
   $(OBJDIR)$(PS)derEncReal10$(OBJ) \
   \
   $(OBJDIR)$(PS)berStrmInitContext$(OBJ) \
   $(OBJDIR)$(PS)berStrmFreeContext$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmBigInt$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmBitStr$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmBMPStr$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmBool$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmCharStr$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmDateStr$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmDateTimeStr$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmDurationStr$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmTimeStr$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmTimeOfDayStr$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmCommon$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmEnum$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmInt8$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmInt16$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmInt64$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmIntValue$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmNull$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmObjId64$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmReal$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmRelativeOID$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmUInt$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmUInt8$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmUInt64$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmUnivStr$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmOpenTypeExt$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmXSDAny$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmBitStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmBigInt$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmBMPStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmCharStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmDateStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmDateTimeStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmDurationStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmTimeStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmTimeOfDayStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmCommon$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmDynBitStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmEnum$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmInt8$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmInt16$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmInt64$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmNextElement$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmNull$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmObjId64$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmOIDSubIds$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmOpenType$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmOpenTypeAppend$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmOpenTypeExt$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmPeekTagAndLen$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmReadTLV$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmReal$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmRelativeOID$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmUInt8$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmUInt64$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmUnivStr$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmBool$(OBJ) \
   $(OBJDIR)$(PS)berSocket$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmDecimal$(OBJ) \
   $(OBJDIR)$(PS)berDecStrmReal10$(OBJ) \
   $(OBJDIR)$(PS)berEncStrmReal10$(OBJ) \
   \
   $(OBJDIR)$(PS)cerEncStrmBMPStr$(OBJ) \
   $(OBJDIR)$(PS)cerEncStrmBitStr$(OBJ) \
   $(OBJDIR)$(PS)cerEncStrmCharStr$(OBJ) \
   $(OBJDIR)$(PS)cerEncStrmOctStr$(OBJ) \
   $(OBJDIR)$(PS)cerEncStrmUnivStr$(OBJ) \
   $(OBJDIR)$(PS)cerEncStrmReal10$(OBJ) \
   $(OBJDIR)$(PS)derEncBitString$(OBJ)

BER_C_OBJECTS_LC = \
   $(LCOBJDIR)$(PS)berDecCharArray$(OBJ) \
   $(LCOBJDIR)$(PS)berDecStrmDynObjId$(OBJ) \
   $(LCOBJDIR)$(PS)berDecStrmDynOctStr$(OBJ) \
   $(LCOBJDIR)$(PS)berDecStrmInt$(OBJ) \
   $(LCOBJDIR)$(PS)berDecStrmUInt$(OBJ) \
   $(LCOBJDIR)$(PS)berDecStrmObjId$(OBJ) \
   $(LCOBJDIR)$(PS)berDecStrmOctStr$(OBJ) \
   $(LCOBJDIR)$(PS)berDecStrmUInt16$(OBJ) \
   $(LCOBJDIR)$(PS)berEncStrmInt$(OBJ) \
   $(LCOBJDIR)$(PS)berEncStrmObjId$(OBJ) \
   $(LCOBJDIR)$(PS)berEncStrmOctStr$(OBJ) \
   $(LCOBJDIR)$(PS)berEncStrmUInt16$(OBJ) \
   $(LCOBJDIR)$(PS)xd_bigint$(OBJ) \
   $(LCOBJDIR)$(PS)xd_bitstr$(OBJ) \
   $(LCOBJDIR)$(PS)xd_bitstr_s$(OBJ) \
   $(LCOBJDIR)$(PS)xd_boolean$(OBJ) \
   $(LCOBJDIR)$(PS)xd_charstr$(OBJ) \
   $(LCOBJDIR)$(PS)xd_datestr$(OBJ) \
   $(LCOBJDIR)$(PS)xd_dynObjId$(OBJ) \
   $(LCOBJDIR)$(PS)xd_timestr$(OBJ) \
   $(LCOBJDIR)$(PS)xd_datetimestr$(OBJ) \
   $(LCOBJDIR)$(PS)xd_timeofdaystr$(OBJ) \
   $(LCOBJDIR)$(PS)xd_durationstr$(OBJ) \
   $(LCOBJDIR)$(PS)xd_integer$(OBJ) \
   $(LCOBJDIR)$(PS)xd_int8$(OBJ) \
   $(LCOBJDIR)$(PS)xd_objid$(OBJ) \
   $(LCOBJDIR)$(PS)xd_octstr$(OBJ) \
   $(LCOBJDIR)$(PS)xd_OpenType$(OBJ) \
   $(LCOBJDIR)$(PS)xd_uint8$(OBJ) \
   $(LCOBJDIR)$(PS)xd_uint16$(OBJ) \
   $(LCOBJDIR)$(PS)xd_unsigned$(OBJ) \
   $(LCOBJDIR)$(PS)xe_bigint$(OBJ) \
   $(LCOBJDIR)$(PS)xe_bitstr$(OBJ) \
   $(LCOBJDIR)$(PS)xe_boolean$(OBJ) \
   $(LCOBJDIR)$(PS)xe_derCanonicalSort$(OBJ) \
   $(LCOBJDIR)$(PS)xe_integer$(OBJ) \
   $(LCOBJDIR)$(PS)xe_int8$(OBJ) \
   $(LCOBJDIR)$(PS)xe_objid$(OBJ) \
   $(LCOBJDIR)$(PS)xe_octstr$(OBJ) \
   $(LCOBJDIR)$(PS)xe_uint8$(OBJ) \
   $(LCOBJDIR)$(PS)xe_uint16$(OBJ) \
   $(LCOBJDIR)$(PS)xe_unsigned$(OBJ)

BER_C_OBJECTS = \
   $(BER_C_OBJECTS_NLC) \
   $(BER_C_OBJECTS_LC)

BER_CPP_OBJECTS = \
   $(OBJDIR)$(PS)asn1BerCppTypes$(OBJ) \
   $(OBJDIR)$(PS)ASN1BEREncodeStream$(OBJ) \
   $(OBJDIR)$(PS)ASN1BERDecodeStream$(OBJ) \
   $(BER_C_OBJECTS)
