#!/bin/sh

SCRIPT_PATH="/usr/local/www/cgi-bin"

# Main
echo "Content-type: text/html"
echo ''

# Check login status - logged out if 0.0.0.0, else returns ip of current client
LOGGED_IP=`/usr/bin/conf_agent SESSION_CHK $REMOTE_ADDR`
if [ "$LOGGED_IP" != "$REMOTE_ADDR" ]; then 
  # Goto timeout page
  echo "<meta http-equiv='refresh' content='0; URL=/rsu-timeout.html ' /> "
  exit 0
fi


# Output to browser
cat << '##EOFEOFEOF1'



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>RSU-5940-Status</title>
    <link rel="stylesheet" href="../assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="../assets/css/Features-Boxed.css">
    <link rel="stylesheet" href="../assets/css/Features-Clean.css">
    <link rel="stylesheet" href="../assets/css/Footer-Basic.css">
    <link rel="stylesheet" href="../assets/css/styles.css">
<style>
.icon {
  font-size: 60px;
  text-align: center;
  margin-top: 20px;
  padding: 10px;
}
.intro-container {
  display: -ms-flexbox;
  display: flex;
}
.circle {
 height: 30px;
 width: 30px;
 border-radius: 50%;
 background: #FFFFFF;
 border: 2px solid gray;
 display: inline-block;
  }
.roundcorner {
height: 100px;
width: 99%;
border-radius: 25px;
border: 2px solid #808080;
padding: 10px;
  }
.divOverflow {
overflow: auto;
overflow-x: hidden;
height: 80px;
margin-left: 2px;
padding-left: 15px;
scrollbar-width: thin;
}
.monospace {
    font-family: "Lucida Console", Courier, monospace;
    color: #000000;
}
</style>
</head>
<body onload="start_timers()" >
##EOFEOFEOF1

source $SCRIPT_PATH/add_navbar.sh 
source $SCRIPT_PATH/add_page_timeout.sh

cat << '##EOFEOFEOF2'
    <div class="features-boxed">
        <div class="container">
            <div class="intro">
            <div class="intro-container">
                <i class="fa fa-globe icon"></i>
                <h2 class="text-center">RSU GNSS Detail</h2>
            </div>
            </div>
            <div class="row justify-content-center features">




<!-- UBlox GPS block -->
<div class="col-sm-5 col-md-4 col-lg-3 text-left item" style="padding-left: 5px;padding-right: 5px;">
    <div class="text-left box shadow p-3 mb-5 bg-white rounded" style="padding-top: 5px; margin-bottom: 0px; min-height: 275px">
        <h3 class='name' style='color: #007BFF' style='margin-bottom: 5px'>UBlox GNSS</h3>
        <br/>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 0px'><span>
        <pre id='ublox_txt'>Loading....</pre>
        </span></div>
        * Note: This GPS data is used for V2X messaging and RSU time and location
    </div>
</div>
<!-- END UBlox GPS block -->


<!-- Kinematics GNSS block -->
<div class="col-sm-5 col-md-5 col-lg-5 col-xl-5 text-left item" style="padding-left: 5px; padding-right: 5px;">
    <div class="text-left box shadow p-3 mb-5 bg-white rounded" style="padding-top: 0px; margin-bottom: 0px; min-height: 350px">
        <h3 class='name' style='color: #007BFF' style='margin-bottom: 16px'>MDM9150 Internal GNSS</h3>
        <br/>
        <div class='name' style='color: #808080; font-size: 15px; margin-top: 0px; padding-top: 0px; margin-bottom: 0px'><span>
        <pre id='kinem_txt'>Loading....</pre>
        </span></div>
        * Note: This GPS data is used for CV2X timing
    </div>
</div>
<!-- END Kinematics GNSS block -->


<!-- ROW-SPANNING DIV to contain STATUS DETAIL and SIGNAL DETAIL blocks -->
<div class='col-sm-4 col-md-4 col-lg-4 item'>

<!-- Status Detail block -->
    <div class='text-left box shadow p-3 mb-5 bg-white rounded' style='padding-top: 5px;margin-bottom: 15px; min-height: 261px; margin-bottom:0px'>
        <h3 class='name' style='color: #007BFF' style='margin-bottom: 16px'>Status Detail</h3>
        <br/>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>GPS Antenna: <span id='gps_ant1' style='color: #000000'></span></div>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>Boot to Position Fix: <span id='ub_posn_fix_time' style='color: #000000'></span> seconds</div>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>Boot to Time Fix: <span id='ub_time_fix_time' style='color: #000000'></span> seconds</div>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>Boot to Time Accuracy of Cv2x: <span id='ub_ok_time_fix_time' style='color: #000000'></span> seconds</div>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>UBlox Firmware version: <span id='ub_fw_ver' style='color: #000000'></span></div>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>UBlox Config: <span id='ub_cfg_ver' style='color: #000000'></span></div>
    </div>
<!-- END Status Detail block -->


<!-- GNSS Signal Detail block -->
    <div class='text-left box shadow p-3 mb-5 bg-white rounded' style='padding-top: 5px;margin-bottom: 15px; min-height: 261px; margin-bottom:0px'>
        <h3 class='name' style='color: #007BFF' style='margin-bottom: 16px'>Signal / Jamming Detail</h3>
        <br/>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>UBlox Noise Level: <span id='ub_noise' style='color: #000000'></span></div>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>UBlox Jamming Indicator: <span id='ub_jam_ind' style='color: #000000'></span></div>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>UBlox Jamming Status: <span id='ub_jam_sts' style='color: #000000'></span></div>
    </div>
<!-- END Status Detail block -->
</div>
<!-- END of ROW-SPANNING DIV to contain STATUS DETAIL and SIGNAL DETAIL blocks -->



<!-- Back block -->
                <div class="col-sm-6 col-md-5 col-lg-3 item">
                  <a href="/cgi-bin/status_display_live">
                    <div class="shadow p-3 mb-5 bg-white rounded"><i class="fa fa-arrow-left icon"></i>
                        <h3 class='name'>Back</h3>
                    </div>
                  </a>
                </div>
<!-- END Back block -->



            </div>
      <h4 class="text-center" id="rsu_time"></h4>
        </div>
    </div>
            <p class="copyright" style='color:#aaa;text-align:center;font-size:13px;margin-bottom: 0px;'>
            </p>
    <div class="footer-basic">
        <footer>
            <p class="copyright">MobiQ © 2023</p>
        </footer>
    </div>
    <script src="../assets/js/jquery.min.js"></script>
    <script src="../assets/bootstrap/js/bootstrap.min.js"></script>
    <script>
    function start_update() {
      if (ready_for_update_request_status == "READY") {
          ready_for_update_request_status = "REQ_SENT";
          send_data_update_request();
      } else {
          ready_for_update_request_status = ready_for_update_request_status + " ... STILL WAITING";
      }
      var t = setTimeout(start_update, 1000);
    }
    var ready_for_update_request_status = "READY";
    function send_data_update_request() {
      var xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
          ready_for_update_request_status = "READY";
          var str = this.responseText;
          var bits_arr = str.split('<COMMA>');

          document.getElementById("kinem_txt").innerHTML = bits_arr[0].trim();
          document.getElementById("ublox_txt").innerHTML = bits_arr[1].trim();
          document.getElementById("ub_posn_fix_time").innerHTML = bits_arr[2];
          document.getElementById("ub_time_fix_time").innerHTML = bits_arr[3];
          document.getElementById("ub_ok_time_fix_time").innerHTML = bits_arr[4];
          document.getElementById("ub_fw_ver").innerHTML = bits_arr[5];
          document.getElementById("ub_cfg_ver").innerHTML = bits_arr[6];
          document.getElementById("gps_ant1").innerHTML = bits_arr[7];
          if (bits_arr[7].trim() == "Connected")
              document.getElementById("gps_ant1").style.color = "green";
          else
            document.getElementById("gps_ant1").style.color = "red";
          document.getElementById("ub_noise").innerHTML = bits_arr[8];
          document.getElementById("ub_jam_ind").innerHTML = bits_arr[9];
          document.getElementById("ub_jam_sts").innerHTML = bits_arr[10];
        }
      };
      xhttp.open("GET", '/cgi-bin/get_gnss_detail_data', true);
      xhttp.send();
    }
    function start_timers() {
      ready_for_update_request_status = "READY";
      start_update();
    }
    </script>
</body>
</html>

##EOFEOFEOF2

