#!/bin/sh

SCRIPT_PATH="/usr/local/www/cgi-bin"
export PATH=/usr/local/bin:$PATH

# Main
echo "Content-type: text/html"
echo ''

# Check login status - logged out if 0.0.0.0, else returns ip of current client
LOGGED_IP=`/usr/bin/conf_agent SESSION_CHK $REMOTE_ADDR`
if [ "$LOGGED_IP" != "$REMOTE_ADDR" ]; then 
  # Goto timeout page
  echo "<meta http-equiv='refresh' content='0; URL=/rsu-timeout.html ' /> "
  exit 0
fi

# Grab some config values to display
I2VRadioType=`/usr/bin/conf_agent READ i2v I2VRadioType`
# Translate I2VRadioType into Human Abbreviation
if [ "$I2VRadioType" == 0 ]; then
    RadioMode=DSRC
    I2VTransmitPower=`/usr/bin/conf_agent READ i2v I2VTransmitPower`
    I2VChannelNumber=`/usr/bin/conf_agent READ i2v I2VUnifiedChannelNumber`
elif [ "$I2VRadioType" == 1 ]; then
    RadioMode=CV2X
    I2VTransmitPower=`/usr/local/bin/dncmdctl cv2xcfg power | head -1`
    I2VChannelNumber=`/usr/local/bin/dncmdctl cv2xcfg channel | head -1`
else
    RadioMode="Illegal value '$I2VRadioType'"
fi


# Output to browser
cat << '##EOFEOFEOF1'
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>RSU-5940-Status</title>
    <link rel="stylesheet" href="../assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="../assets/css/Features-Boxed.css">
    <link rel="stylesheet" href="../assets/css/Features-Clean.css">
    <link rel="stylesheet" href="../assets/css/Footer-Basic.css">
    <link rel="stylesheet" href="../assets/css/styles.css">
<style>
.icon {
  font-size: 60px;
  text-align: center;
  margin-top: 20px;
  padding: 10px;
}
.intro-container {
  display: -ms-flexbox;
  display: flex;
}
.circle {
 height: 30px;
 width: 30px;
 border-radius: 50%;
 background: #FFFFFF;
 border: 2px solid gray;
 display: inline-block;
  }
.roundcorner {
height: 100px;
width: 99%;
border-radius: 25px;
border: 2px solid #808080;
padding: 10px;
  }
.divOverflow {
overflow: auto;
overflow-x: hidden;
height: 80px;
margin-left: 2px;
padding-left: 15px;
scrollbar-width: thin;
}
.monospace {
    font-family: "Lucida Console", Courier, monospace;
    color: #000000;
}
</style>
</head>
<body onload="start_timers()" >
##EOFEOFEOF1

source $SCRIPT_PATH/add_navbar.sh 
source $SCRIPT_PATH/add_page_timeout.sh

cat << '##EOFEOFEOF2'
    <div class="features-boxed">
        <div class="container">
            <div class="intro">
            <div class="intro-container">
                <i class="fa fa-feed icon"></i>
                <h2 class="text-center">RSU Radio Detail</h2>
            </div>
            </div>
            <div class="row justify-content-center features">


<!-- Radio Status block -->
<div class='col-sm-4 col-md-5 col-lg-3 item'>
    <div class='text-left box shadow p-3 mb-5 bg-white rounded' style='padding-top: 5px;margin-bottom: 15px; min-height: 261px; margin-bottom:0px'>
        <h3 class='name' style='color: #007BFF' style='margin-bottom: 16px'>Radio Status</h3>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>CV2X Tx Status: <span id='cv2x_tx_status' style='color: #000000'></span></div>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>CV2X Rx Status: <span id='cv2x_rx_status' style='color: #000000'></span></div>
        <!-- <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>DSRC Status: <span id='dsrc_status'  style='color: #000000'></span></div> -->
    </div>
</div>

<!-- Radio Activity block -->
<div class='col-sm-4 col-md-5 col-lg-3 item'>
    <!-- <div class='text-left box shadow p-3 mb-5 bg-white rounded'> -->
    <!-- Copying inner div from RSU Services Active box -->
    <div class='text-left box shadow p-3 mb-5 bg-white rounded' style='padding-top: 5px;margin-bottom: 15px; min-height: 261px; margin-bottom:0px'>
        <h3 class='name' style='color: #007BFF' style='margin-bottom: 16px'>Radio Activity</h3>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>CV2X Tx: <span id='radio_cv2x_tx' style='color: #000000'></span></div>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>CV2X Rx: <span id='radio_cv2x_rx' style='color: #000000'></span></div>
        <!-- <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>DSRC Tx: <span id='radio_dsrc_tx'  style='color: #000000'></span></div> -->
        <!-- <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>DSRC Rx: <span id='radio_dsrc_rx'  style='color: #000000'></span></div> -->
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>Radio Channel: <span id='radio_channel'  style='color: #000000'></span></div>
        <div id='radio_placeholder'>&nbsp</div>
    </div>
</div>



<!-- Antenna Status block -->
<div class='col-sm-4 col-md-4 col-lg-4 item'>
    <div class='text-left box shadow p-3 mb-5 bg-white rounded' style='padding-top: 5px;margin-bottom: 15px; min-height: 261px; margin-bottom:0px'>
        <h3 class='name' style='color: #007BFF' style='margin-bottom: 16px'>Antenna Status</h3>

          <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>CV2X Antenna 1: <span id='cv2x_ant1' style='color: #000000'></span></div>
          <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>CV2X Antenna 2: <span id='cv2x_ant2' style='color: #000000'></span></div>
          <!-- <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>DSRC Antenna 1: <span id='dsrc_ant1' style='color: #000000'></span></div> -->
          <!-- <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>DSRC Antenna 2: <span id='dsrc_ant2' style='color: #000000'></span></div> -->
          <!-- <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>RFSW Antenna 1: <span id='rfsw_ant1' style='color: #000000'></span></div> -->
          <!-- <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>RFSW Antenna 2: <span id='rfsw_ant2' style='color: #000000'></span></div> -->

    </div>
</div>



    <!-- Security Activity -->
    <div class='row justify-content-center features' style='padding-top: 0px;padding-bottom: 0px;'>
    <div class="col-sm-7 col-md-7 col-lg-7 col-xl-7 text-left item" style="padding-left: 5px;padding-right: 5px;">
        <div class="text-left box shadow p-3 mb-5 bg-white rounded" style="padding-top: 5px;margin-bottom: 15px; min-height: 230px; margin-bottom:0px">
            <h3 class='name' style='color: #007BFF' style='margin-bottom: 16px'>Radio Message Security Activity</h3>
            <br/>
            <table align=center>
                <tr><td></td>
                    <td><div class="name" style='color: #808080; font-size: 15px; margin-bottom: 7px'> &nbsp; &nbsp; Requests</div></td>
                    <td><div class="name" style='color: #808080; font-size: 15px; margin-bottom: 7px'> &nbsp; &nbsp; Successes</div></td>
                    <td><div class="name" style='color: #808080; font-size: 15px; margin-bottom: 7px'> &nbsp; &nbsp; Failures</div></td>
                </tr>
                <tr><td><div class="name" style='color: #808080; font-size: 15px; margin-bottom: 7px'>Signs</td>
                    <td><div id='metric_1' class="name text-right" style='color: #000000; font-size: 15px; margin-bottom: 7px'></div></td>
                    <td><div id='metric_2' class="name text-right" style='color: #000000; font-size: 15px; margin-bottom: 7px'></div></td>
                    <td><div id='metric_3' class="name text-right" style='color: #000000; font-size: 15px; margin-bottom: 7px'></div></td>
                </tr>
                <tr><td><div class="name" style='color: #808080; font-size: 15px; margin-bottom: 7px'>Strips</div></td>
                    <td><div id='metric_4' class="name text-right" style='color: #000000; font-size: 15px; margin-bottom: 7px'></div></td>
                    <td><div id='metric_5' class="name text-right" style='color: #000000; font-size: 15px; margin-bottom: 7px'></div></td>
                    <td><div id='metric_6' class="name text-right" style='color: #000000; font-size: 15px; margin-bottom: 7px'></div></td>
                </tr>
                <tr><td><div class="name" style='color: #808080; font-size: 15px; margin-bottom: 7px'>Verifies</div></td>
                    <td><div id='metric_7' class="name text-right" style='color: #000000; font-size: 15px; margin-bottom: 7px'></div></td>
                    <td><div id='metric_8' class="name text-right" style='color: #000000; font-size: 15px; margin-bottom: 7px'></div></td>
                    <td><div id='metric_9' class="name text-right" style='color: #000000; font-size: 15px; margin-bottom: 7px'></div></td>
                </tr>
            </table>
        </div>
    </div>
    <!-- END Security Activity -->




<!-- Radio Configuration block -->
<div class='col-sm-5 col-md-5 col-lg-5 item'>
    <!-- <div class='text-left box shadow p-3 mb-5 bg-white rounded'> -->
    <!-- Copying inner div from RSU Services Active box -->
    <div class='text-left box shadow p-3 mb-5 bg-white rounded' style='padding-top: 5px;margin-bottom: 15px; min-height: 230px; margin-bottom:0px'>
        <h3 class='name' style='color: #007BFF' style='margin-bottom: 16px'>Radio Configuration</h3>
##EOFEOFEOF2
# Echos to output with vars
    echo "        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>Radio Mode: <span style='color: #000000'>$RadioMode</span></div>"
    echo "        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>CV2X Transmit Channel: <span style='color: #000000'>$I2VChannelNumber</span></div>"
    echo "        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>Transmit Power(db): <span style='color: #000000'>$I2VTransmitPower</span></div>"
cat << '##EOFEOFEOF3'
    </div>
</div>


<!-- Radio Temperatures block -->
<div class='col-sm-4 col-md-5 col-lg-3 item'>
    <div class='text-left box shadow p-3 mb-5 bg-white rounded' style='padding-top: 5px;margin-bottom: 15px; min-height: 195px; margin-bottom:0px'>
        <h3 class='name' style='color: #007BFF' style='margin-bottom: 16px'>Radio Temperatures</h3>
        <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>CV2X Temp: <span id='cv2x_cpu_temp' style='color: #000000'></span></div>
        <!-- <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>DSRC Temp: <span id='dsrc_temp' style='color: #000000'></span></div> -->
        <!-- <div class='name' style='color: #808080; font-size: 15px; margin-bottom: 7px'>HSM Temp: <span id='hsm_temp' style='color: #000000'></span></div> -->
    </div>
</div>


<!-- Home block -->
                <div class="col-sm-6 col-md-5 col-lg-3 item">
                  <a href="/cgi-bin/status_display_live">
                    <div class="shadow p-3 mb-5 bg-white rounded"><i class="fa fa-arrow-left icon"></i>
                        <!-- Original Home
                        <h3 class='name' style='margin-bottom: 74px'>Home</h3>
                        -->
                        <h3 class='name'>Back</h3>
                    </div>
                  </a>
                </div>

            </div>
        </div>
    </div>

            <p class="copyright" style='color:#aaa;text-align:center;font-size:13px;margin-bottom: 0px;'>
            </p>
    <div class="footer-basic">
        <footer>
            <p class="copyright">MobiQ © 2023</p>
        </footer>
    </div>
    <script src="../assets/js/jquery.min.js"></script>
    <script src="../assets/bootstrap/js/bootstrap.min.js"></script>
    <script>
    function rsu_time_refresh() {
      var t = setTimeout(rsu_time_refresh, 1000);
      if (msec > 0) {
         msec = msec + 1000;
         var n_date = new Date(msec);
         var utc_date = n_date.toUTCString();
         var utc_date = utc_date.replace("GMT", "UTC");
         document.getElementById("rsu_time").innerHTML = utc_date;
      }
    };
    function start_update() {
      if (ready_for_update_request_status == "READY") {
          ready_for_update_request_status = "REQ_SENT";
          send_update_kaio_refresh();
      } else {
          ready_for_update_request_status = ready_for_update_request_status + " ... STILL WAITING";
      }
      var t = setTimeout(start_update, 1000);
    }
  function process_new_spat_status(spat_arr) {
              var div_overflow = document.getElementById("divOverFlow");
              var div_no_data = document.getElementById("divNoData");
              spat_arr[0] = spat_arr[0].replace(/\s+/g, ' ').trim();
              if (spat_arr[0] == 'True')  {
                  div_no_data.style.display = "none";
                  div_overflow.style.display = "inline-block";
                  var phase = "phase_";
                  var led_phase = "led_phase_";
                  var led_element = "";
                  var temp = "";
                  var divPhase = "divPhase";
                  var div_phase = "";
                  var j = 0;
                  for (i = 1; i < 9; i++) {
                      temp = led_phase + i;
                      led_element = document.getElementById(temp);
                      spat_arr[i + j] = spat_arr[i + j].replace(/\s+/g, ' ').trim();
                      led_element.style.background = spat_arr[i + j];
                      temp = phase + i;
                      if (spat_arr[i*2] < 10) {
                          document.getElementById(temp).innerHTML = 'Phase ' + i + ':&nbsp;<span class="monospace"> &nbsp;' + spat_arr[i*2] + "</span>";
                      } else if (spat_arr[i*2] < 100) {
                          document.getElementById(temp).innerHTML = 'Phase ' + i + ':&nbsp;<span class="monospace"> ' + spat_arr[i*2] + "</span>";
                      } else {
                          document.getElementById(temp).innerHTML = 'Phase ' + i + ':&nbsp;<span class="monospace">' + spat_arr[i*2] + "</span>";
                      }
                      temp = divPhase + i;
                      div_phase = document.getElementById(temp);
                      if (spat_arr[i + j] == "0") {
                          div_phase.style.display = "none";
                      } else {
                          div_phase.style.display = "";
                      }
                      j++;
                  }
              } else {
                  div_no_data.style.display = "inline-block";
                  div_overflow.style.display = "none";
              }
  }
  function set_green_or_red(element_name, green_value, current_value) {
      if (current_value.trim() == green_value) {
          document.getElementById(element_name).style.color = "green";
      } else {
          document.getElementById(element_name).style.color = "red";
      }
  }
    var ready_for_update_request_status = "READY";
    function send_update_kaio_refresh() {
      var xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
          ready_for_update_request_status = "READY";
          var str = this.responseText;
          var bits_arr = str.split(',');
          document.getElementById("radio_cv2x_tx").innerHTML = bits_arr[0];
          //document.getElementById("radio_dsrc_tx").innerHTML = bits_arr[1];
          document.getElementById("radio_cv2x_rx").innerHTML = bits_arr[2];
          //document.getElementById("radio_dsrc_rx").innerHTML = bits_arr[3];
          document.getElementById("radio_channel").innerHTML = bits_arr[4];

          // Change the radio channel to cv2x's channel if cv2x is active
          if (bits_arr[5].trim() != 'DSRC') {
              document.getElementById("radio_channel").innerHTML = 'CV2X:' + bits_arr[5];
          }

          // CV2X RX:Active TX: Active [6] [7]
          document.getElementById("cv2x_rx_status").innerHTML = bits_arr[6];
          document.getElementById("cv2x_tx_status").innerHTML = bits_arr[7];

          // DSRC Radio status - up or down [8]
          // document.getElementById("dsrc_status").innerHTML = bits_arr[8];

          // SKIP [9] - RH850 data for power input voltage

          // SKIP [10] - GPS antenna

          // Radio Antennas [11 - 16]
          document.getElementById("cv2x_ant1").innerHTML = bits_arr[11];
          document.getElementById("cv2x_ant2").innerHTML = bits_arr[12];
          //document.getElementById("rfsw_ant1").innerHTML = bits_arr[13];
          //document.getElementById("rfsw_ant2").innerHTML = bits_arr[14];
          //document.getElementById("dsrc_ant1").innerHTML = bits_arr[15];
          //document.getElementById("dsrc_ant2").innerHTML = bits_arr[16];

          // Radio Security Activity [17-25]
          for (i = 0; i < 9; i++) {
            document.getElementById("metric_" + (i+1)).innerHTML = bits_arr[i + 17];
          }
          // Radio Temps [26 - 29]
          document.getElementById("cv2x_cpu_temp").innerHTML = bits_arr[26] + ' C';
          //    NOTE: No longer displaying [27] -- cv2x pmic temp
          //document.getElementById("dsrc_temp").innerHTML = bits_arr[28] + ' C';
          document.getElementById("hsm_temp").innerHTML = bits_arr[29] + ' C';
        }
      };
      xhttp.open("GET", '/cgi-bin/get_radio_detail_data', true);
      xhttp.send();
    }
    function start_timers() {
      start_update();
      var t = setTimeout(rsu_time_refresh, 1000);
    }
    </script>

</body>
</html>
##EOFEOFEOF3
