LIBXML2OBJ = \
$(OBJDIR)$(PS)buf$(OBJ) \
$(OBJDIR)$(PS)chvalid$(OBJ) \
$(OBJDIR)$(PS)catalog$(OBJ) \
$(OBJDIR)$(PS)debugXML$(OBJ) \
$(OBJDIR)$(PS)dict$(OBJ) \
$(OBJDIR)$(PS)encoding$(OBJ) \
$(OBJDIR)$(PS)entities$(OBJ) \
$(OBJDIR)$(PS)error$(OBJ) \
$(OBJDIR)$(PS)globals$(OBJ) \
$(OBJDIR)$(PS)hash$(OBJ) \
$(OBJDIR)$(PS)HTMLparser$(OBJ) \
$(OBJDIR)$(PS)HTMLtree$(OBJ) \
$(OBJDIR)$(PS)legacy$(OBJ) \
$(OBJDIR)$(PS)list$(OBJ) \
$(OBJDIR)$(PS)parser$(OBJ) \
$(OBJDIR)$(PS)parserInternals$(OBJ) \
$(OBJDIR)$(PS)pattern$(OBJ) \
$(OBJDIR)$(PS)relaxng$(OBJ) \
$(OBJDIR)$(PS)SAX2$(OBJ) \
$(OBJDIR)$(PS)SAX$(OBJ) \
$(OBJDIR)$(PS)threads$(OBJ) \
$(OBJDIR)$(PS)tree$(OBJ) \
$(OBJDIR)$(PS)uri$(OBJ) \
$(OBJDIR)$(PS)valid$(OBJ) \
$(OBJDIR)$(PS)xinclude$(OBJ) \
$(OBJDIR)$(PS)xlink$(OBJ) \
$(OBJDIR)$(PS)xmlIO$(OBJ) \
$(OBJDIR)$(PS)xmlmemory$(OBJ) \
$(OBJDIR)$(PS)xmlregexp$(OBJ) \
$(OBJDIR)$(PS)xmlmodule$(OBJ) \
$(OBJDIR)$(PS)xmlsave$(OBJ) \
$(OBJDIR)$(PS)xmlunicode$(OBJ) \
$(OBJDIR)$(PS)xpath$(OBJ) \
$(OBJDIR)$(PS)xpointer$(OBJ) \
$(OBJDIR)$(PS)xmlreader$(OBJ) \
$(OBJDIR)$(PS)xmlstring$(OBJ) \
$(OBJDIR)$(PS)xmlschemas$(OBJ) \
$(OBJDIR)$(PS)xmlschemastypes$(OBJ)

