/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.7.0, Date: 25-May-2023.
 *
 * Command:  asn1c CooperativeControlMsg-v1-ph.asn J2735-AddGrpB.asn J2735-AddGrpC.asn J2735-BasicSafetyMessage-v4.asn J2735-CommonSafetyRequest.asn J2735-Common-v7.asn J2735-EmergencyVehicleAlert.asn J2735-IntersectionCollision.asn J2735-ITIS.asn J2735-MapData-v1.asn J2735-MessageFrame-v5.asn J2735-NMEAcorrections.asn J2735-NTCIP.asn J2735-PersonalSafetyMessage.asn J2735-ProbeDataManagement.asn J2735-ProbeVehicleData.asn J2735-REGION.asn J2735-RoadSideAlert.asn J2735-RTCMcorrections.asn J2735-SignalRequestMessage.asn J2735-SignalStatusMessage.asn J2735-SPAT-v2.asn J2735-TestMessage00.asn J2735-TestMessage01.asn J2735-TestMessage02.asn J2735-TestMessage03.asn J2735-TestMessage04.asn J2735-TestMessage05.asn J2735-TestMessage06.asn J2735-TestMessage07.asn J2735-TestMessage08.asn J2735-TestMessage09.asn J2735-TestMessage10.asn J2735-TestMessage11.asn J2735-TestMessage12.asn J2735-TestMessage13.asn J2735-TestMessage14.asn J2735-TestMessage15.asn J2735-TravelerInformation-v2.asn MnvrSharingCoordMsg-v1-ph.asn PersonalSafetyMsg2-v1-ph.asn ProbeDataConfig-v0.30.asn ProbeDataReport-v0.30.asn RoadGeoAttributes-v2-ph.asn RoadSafetyMsg-v1-ph.asn RoadWeatherMessage.asn SensorDataSharingMsg-v1-ph.asn SignalControlAndPrioritizationRequest-v1-ph.asn SignalControlAndPrioritizationStatus-v1-ph.asn TollAdvertisementMsg-v0.10-ph.asn TollUsageAckMsg-v0.10-ph.asn TollUsageMsg-v0.10-ph.asn TrafficSignalPhaseAndTiming-v1-ph.asn -c -per -compact
 */
#ifndef EMERGENCYVEHICLEALERT_H
#define EMERGENCYVEHICLEALERT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "rtkey.h"
#include "rtpersrc/asn1per.h"

#include "ITIS.h"

/**
 * Header file for ASN.1 module EmergencyVehicleAlert
 */
/**************************************************************/
/*                                                            */
/*  EmergencyVehicleAlert_regional                            */
/*                                                            */
/**************************************************************/
/*
Type was extracted from 'EmergencyVehicleAlert'
*/
struct EXTERN RegionalExtension;

/* List of RegionalExtension */
typedef OSRTDList EmergencyVehicleAlert_regional;

EXTERN int asn1PE_EmergencyVehicleAlert_regional (OSCTXT* pctxt, EmergencyVehicleAlert_regional* pvalue);

EXTERN int asn1PD_EmergencyVehicleAlert_regional (OSCTXT* pctxt, EmergencyVehicleAlert_regional* pvalue);

EXTERN int asn1Init_EmergencyVehicleAlert_regional (
   EmergencyVehicleAlert_regional* pvalue);

/**************************************************************/
/*                                                            */
/*  EmergencyVehicleAlert                                     */
/*                                                            */
/**************************************************************/
/*
EmergencyVehicleAlert ::= SEQUENCE {
   timeStamp [0] MinuteOfTheYear OPTIONAL,
   id [1] TemporaryID OPTIONAL,
   rsaMsg [2] RoadSideAlert,
     -- the DSRCmsgID inside this
                   -- data frame is set as per the
                   -- RoadSideAlert.
   responseType [3] ResponseType OPTIONAL,
   details [4] EmergencyDetails OPTIONAL,
                   -- Combines these 3 items:
                   -- SirenInUse,
                   -- LightbarInUse,
                   -- MultiVehicleReponse,
   mass [5] VehicleMass OPTIONAL,
   basicType [6] VehicleType OPTIONAL,
                                -- gross size and axle cnt
   -- type of vehicle and agency when known
   vehicleType [7] VehicleGroupAffected OPTIONAL,
   responseEquip [8] IncidentResponseEquipment OPTIONAL,
   responderType [9] ResponderGroupAffected OPTIONAL,
   regional [10] SEQUENCE (SIZE (1..4)) OF RegionalExtension OPTIONAL,
   ...
}
*/
typedef struct EXTERN EmergencyVehicleAlert {
   struct {
      OSUINT8 timeStampPresent : 1;
      OSUINT8 idPresent : 1;
      OSUINT8 responseTypePresent : 1;
      OSUINT8 detailsPresent : 1;
      OSUINT8 massPresent : 1;
      OSUINT8 basicTypePresent : 1;
      OSUINT8 vehicleTypePresent : 1;
      OSUINT8 responseEquipPresent : 1;
      OSUINT8 responderTypePresent : 1;
      OSUINT8 regionalPresent : 1;
   } m;
   OSUINT32 timeStamp;
   struct TemporaryID *id;
   struct RoadSideAlert *rsaMsg;
   OSUINT8 responseType;
   struct EmergencyDetails *details;
   OSUINT8 mass;
   OSUINT8 basicType;
   VehicleGroupAffected vehicleType;
   IncidentResponseEquipment responseEquip;
   ResponderGroupAffected responderType;
   EmergencyVehicleAlert_regional regional;
   OSRTDList extElem1;
} EmergencyVehicleAlert;

EXTERN int asn1PE_EmergencyVehicleAlert (OSCTXT* pctxt, EmergencyVehicleAlert* pvalue);

EXTERN int asn1PD_EmergencyVehicleAlert (OSCTXT* pctxt, EmergencyVehicleAlert* pvalue);

EXTERN int asn1Init_EmergencyVehicleAlert (EmergencyVehicleAlert* pvalue);

#ifdef __cplusplus
}
#endif

#endif
