/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.7.0, Date: 25-May-2023.
 *
 * Command:  asn1c CooperativeControlMsg-v1-ph.asn J2735-AddGrpB.asn J2735-AddGrpC.asn J2735-BasicSafetyMessage-v4.asn J2735-CommonSafetyRequest.asn J2735-Common-v7.asn J2735-EmergencyVehicleAlert.asn J2735-IntersectionCollision.asn J2735-ITIS.asn J2735-MapData-v1.asn J2735-MessageFrame-v5.asn J2735-NMEAcorrections.asn J2735-NTCIP.asn J2735-PersonalSafetyMessage.asn J2735-ProbeDataManagement.asn J2735-ProbeVehicleData.asn J2735-REGION.asn J2735-RoadSideAlert.asn J2735-RTCMcorrections.asn J2735-SignalRequestMessage.asn J2735-SignalStatusMessage.asn J2735-SPAT-v2.asn J2735-TestMessage00.asn J2735-TestMessage01.asn J2735-TestMessage02.asn J2735-TestMessage03.asn J2735-TestMessage04.asn J2735-TestMessage05.asn J2735-TestMessage06.asn J2735-TestMessage07.asn J2735-TestMessage08.asn J2735-TestMessage09.asn J2735-TestMessage10.asn J2735-TestMessage11.asn J2735-TestMessage12.asn J2735-TestMessage13.asn J2735-TestMessage14.asn J2735-TestMessage15.asn J2735-TravelerInformation-v2.asn MnvrSharingCoordMsg-v1-ph.asn PersonalSafetyMsg2-v1-ph.asn ProbeDataConfig-v0.30.asn ProbeDataReport-v0.30.asn RoadGeoAttributes-v2-ph.asn RoadSafetyMsg-v1-ph.asn RoadWeatherMessage.asn SensorDataSharingMsg-v1-ph.asn SignalControlAndPrioritizationRequest-v1-ph.asn SignalControlAndPrioritizationStatus-v1-ph.asn TollAdvertisementMsg-v0.10-ph.asn TollUsageAckMsg-v0.10-ph.asn TollUsageMsg-v0.10-ph.asn TrafficSignalPhaseAndTiming-v1-ph.asn -c -per -compact
 */
#ifndef MESSAGEFRAME_H
#define MESSAGEFRAME_H

#ifdef __cplusplus
extern "C" {
#endif

#include "rtkey.h"
#include "rtpersrc/asn1per.h"

#include "RoadSafetyMessage.h"
#include "TollAdvertisementMessage.h"
#include "TollUsageMessage.h"
#include "TollUsageAckMessage.h"
#include "CooperativeControlMessage.h"
#include "SensorDataSharingMessage.h"
#include "ManeuverSharingAndCoordinatingMessage.h"
#include "RoadGeometryAndAttributes.h"
#include "PersonalSafetyMessage2.h"
#include "TrafficSignalPhaseAndTiming.h"
#include "SignalControlAndPrioritizationRequest.h"
#include "SignalControlAndPrioritizationStatus.h"

/**
 * Header file for ASN.1 module MessageFrame
 */
/**************************************************************/
/*                                                            */
/*  DSRCmsgID                                                 */
/*                                                            */
/**************************************************************/
/*
DSRCmsgID ::= INTEGER (0..32767)
*/
typedef OSUINT16 DSRCmsgID;

EXTERN int asn1PE_DSRCmsgID (OSCTXT* pctxt, DSRCmsgID value);

EXTERN int asn1PD_DSRCmsgID (OSCTXT* pctxt, DSRCmsgID* pvalue);

/**************************************************************/
/*                                                            */
/*  MessageFrame                                              */
/*                                                            */
/**************************************************************/
/*
 -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
 
 Start of entries from table Messages...
 This table typically contains message entries.
 -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
 
MessageFrame ::= SEQUENCE {
   messageId [0] MESSAGE-ID-AND-TYPE.&id ({MessageTypes}),
   value [1] EXPLICIT MESSAGE-ID-AND-TYPE.&Type ({MessageTypes}{@.messageId}),
   ...
}
*/
typedef struct EXTERN MessageFrame {
   DSRCmsgID messageId;
   ASN1OpenType value;
   OSRTDList extElem1;
} MessageFrame;

EXTERN int asn1PE_MessageFrame (OSCTXT* pctxt, MessageFrame* pvalue);

EXTERN int asn1PD_MessageFrame (OSCTXT* pctxt, MessageFrame* pvalue);

EXTERN int asn1Init_MessageFrame (MessageFrame* pvalue);

/* Value definitions */

#define ASN1V_mapData 18
#define ASN1V_signalPhaseAndTimingMessage 19
#define ASN1V_basicSafetyMessage 20
#define ASN1V_commonSafetyRequest 21
#define ASN1V_emergencyVehicleAlert 22
#define ASN1V_intersectionCollision 23
#define ASN1V_nmeaCorrections 24
#define ASN1V_probeDataManagement 25
#define ASN1V_probeVehicleData 26
#define ASN1V_roadSideAlert 27
#define ASN1V_rtcmCorrections 28
#define ASN1V_signalRequestMessage 29
#define ASN1V_signalStatusMessage 30
#define ASN1V_travelerInformation 31
#define ASN1V_personalSafetyMessage 32
#define ASN1V_roadSafetyMessage 33
#define ASN1V_roadWeatherMessage 34
#define ASN1V_probeDataConfigMessage 35
#define ASN1V_probeDataReportMessage 36
#define ASN1V_tollAdvertisementMessage 37
#define ASN1V_tollUsageMessage 38
#define ASN1V_tollUsageAckMessage 39
#define ASN1V_cooperativeControlMessage 40
#define ASN1V_sensorDataSharingMessage 41
#define ASN1V_maneuverSharingAndCoordinatingMessage 42
#define ASN1V_roadGeometryAndAttributes 43
#define ASN1V_personalSafetyMessage2 44
#define ASN1V_trafficSignalPhaseAndTiming 45
#define ASN1V_signalControlAndPrioritizationRequest 46
#define ASN1V_signalControlAndPrioritizationStatus 47
#define ASN1V_testMessage00 240
#define ASN1V_testMessage01 241
#define ASN1V_testMessage02 242
#define ASN1V_testMessage03 243
#define ASN1V_testMessage04 244
#define ASN1V_testMessage05 245
#define ASN1V_testMessage06 246
#define ASN1V_testMessage07 247
#define ASN1V_testMessage08 248
#define ASN1V_testMessage09 249
#define ASN1V_testMessage10 250
#define ASN1V_testMessage11 251
#define ASN1V_testMessage12 252
#define ASN1V_testMessage13 253
#define ASN1V_testMessage14 254
#define ASN1V_testMessage15 255

#ifdef __cplusplus
}
#endif

#endif
