ASN1CXerOpenType$(OBJ): \
    $(OSROOTDIR)/rtxsrc/rtxSList.h \
    $(OSROOTDIR)/rtxsrc/OSRTCtxtHolderIF.h \
    $(XERSRCDIR)/ASN1CXerOpenType.cpp \
    $(OSROOTDIR)/rtsrc/asn1CppEvtHndlr64.h \
    $(OSROOTDIR)/rtxersrc/rtSAXDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxMemory.h \
    $(OSROOTDIR)/rtxsrc/OSRTMsgBufIF.h \
    $(OSROOTDIR)/rtxsrc/rtxUTF8.h \
    $(XERSRCDIR)/asn1XerCppTypes.h \
    $(OSROOTDIR)/rtsrc/asn1CEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/OSRTCtxtHolder.h \
    $(OSROOTDIR)/rtsrc/ASN1TObjId.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlExternDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxPattern.h \
    $(OSROOTDIR)/rtxsrc/rtxBitString.h \
    $(OSROOTDIR)/rtxsrc/rtxDynPtrArray.h \
    $(OSROOTDIR)/rtxsrc/rtxCommonDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxStack.h \
    $(OSROOTDIR)/rtxsrc/rtxExternDefs.h \
    $(OSROOTDIR)/rtxsrc/OSRTInputStreamIF.h \
    $(OSROOTDIR)/rtsrc/asn1tag.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxCppParserIF.h \
    $(OSROOTDIR)/rtxmlsrc/osrtxml.h \
    $(OSROOTDIR)/rtsrc/ASN1TOctStr64.h \
    $(OSROOTDIR)/rtsrc/asn1CppEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/rtxCharStr.h \
    $(OSROOTDIR)/rtxsrc/rtxXmlQName.h \
    $(OSROOTDIR)/rtxsrc/rtxEnum.h \
    $(OSROOTDIR)/rtxsrc/rtxError.h \
    $(OSROOTDIR)/rtxsrc/rtxUtil.h \
    $(OSROOTDIR)/rtxsrc/OSRTMsgBuf.h \
    $(OSROOTDIR)/rtxsrc/rtxContext.h \
    $(OSROOTDIR)/rtsrc/ASN1Context.h \
    $(OSROOTDIR)/rtxsrc/rtxDateTime.h \
    $(OSROOTDIR)/rtxsrc/rtxErrCodes.h \
    $(OSROOTDIR)/rtxsrc/osMacros.h \
    $(OSROOTDIR)/rtxsrc/rtxBuffer.h \
    $(OSROOTDIR)/rtxersrc/ASN1CXerOpenType.h \
    $(OSROOTDIR)/rtxsrc/OSRTContext.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlNamespace.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxCppParser.h \
    $(OSROOTDIR)/rtxersrc/asn1xer.h \
    $(OSROOTDIR)/rtxsrc/rtxReal.h \
    $(OSROOTDIR)/rtxsrc/rtxDiag.h \
    $(OSROOTDIR)/rtsrc/asn1CppTypes.h \
    $(OSROOTDIR)/rtsrc/rtContext.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxDefs.h \
    $(OSROOTDIR)/rtxsrc/OSRTStreamIF.h \
    $(OSROOTDIR)/rtsrc/ASN1TOctStr.h \
    $(OSROOTDIR)/rtsrc/asn1type.h \
    $(OSROOTDIR)/rtxsrc/rtxCommon.h \
    $(OSROOTDIR)/rtxsrc/rtxBigInt.h \
    $(OSROOTDIR)/rtxsrc/osSysTypes.h \
    $(OSROOTDIR)/rtxsrc/rtxFile.h \
    $(OSROOTDIR)/rtxsrc/rtxDList.h \
    $(OSROOTDIR)/rtxsrc/rtxMemBuf.h \
    $(OSROOTDIR)/rtsrc/asn1ErrCodes.h \
    $(OSROOTDIR)/rtsrc/rtExternDefs.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlErrCodes.h
	$(CCC) $(XERCFLAGS) -c -I$(OSROOTDIR) $(IPATHS_) $(XERSRCDIR)/ASN1CXerOpenType.cpp

asn1XerCppTypes$(OBJ): \
    $(OSROOTDIR)/rtxsrc/osMacros.h \
    $(OSROOTDIR)/rtxsrc/OSRTContext.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlNamespace.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxCppParser.h \
    $(OSROOTDIR)/rtxsrc/rtxContext.h \
    $(OSROOTDIR)/rtxsrc/rtxDateTime.h \
    $(OSROOTDIR)/rtsrc/ASN1Context.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxContext.hh \
    $(OSROOTDIR)/rtxsrc/rtxDiag.h \
    $(OSROOTDIR)/rtsrc/asn1CppTypes.h \
    $(OSROOTDIR)/rtxsrc/rtxBigInt.h \
    $(OSROOTDIR)/rtxsrc/osSysTypes.h \
    $(OSROOTDIR)/rtxsrc/OSRTStreamIF.h \
    $(OSROOTDIR)/rtsrc/asn1type.h \
    $(OSROOTDIR)/rtsrc/asn1ErrCodes.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlErrCodes.h \
    $(OSROOTDIR)/rtsrc/rtExternDefs.h \
    $(OSROOTDIR)/rtxsrc/OSRTMsgBufIF.h \
    $(OSROOTDIR)/rtxsrc/rtxMemory.h \
    $(OSROOTDIR)/rtsrc/ASN1TObjId.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlExternDefs.h \
    $(OSROOTDIR)/rtsrc/asn1intl.h \
    $(OSROOTDIR)/rtxsrc/rtxBitString.h \
    $(OSROOTDIR)/rtxsrc/rtxUTF8.h \
    $(OSROOTDIR)/rtsrc/asn1CEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/OSRTInputStreamIF.h \
    $(OSROOTDIR)/rtsrc/asn1tag.h \
    $(OSROOTDIR)/rtxsrc/rtxDynPtrArray.h \
    $(OSROOTDIR)/rtxsrc/rtxEnum.h \
    $(OSROOTDIR)/rtxsrc/rtxError.h \
    $(OSROOTDIR)/rtxersrc/xed_common.hh \
    $(OSROOTDIR)/rtsrc/asn1CppEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/rtxBuffer.h \
    $(OSROOTDIR)/rtxsrc/rtxReal.h \
    $(OSROOTDIR)/rtxersrc/asn1xer.h \
    $(OSROOTDIR)/rtxsrc/OSRTMsgBuf.h \
    $(OSROOTDIR)/rtxsrc/rtxErrCodes.h \
    $(OSROOTDIR)/rtsrc/rt_common.hh \
    $(OSROOTDIR)/rtsrc/rtContext.h \
    $(OSROOTDIR)/rtsrc/ASN1TOctStr.h \
    $(OSROOTDIR)/rtxsrc/rtxCommon.h \
    $(XERSRCDIR)/asn1XerCppTypes.cpp \
    $(OSROOTDIR)/rtxsrc/rtxMemBuf.h \
    $(OSROOTDIR)/rtxsrc/rtxFile.h \
    $(OSROOTDIR)/rtxsrc/rtxDList.h \
    $(OSROOTDIR)/rtxsrc/rtxSList.h \
    $(OSROOTDIR)/rtxsrc/OSRTCtxtHolderIF.h \
    $(OSROOTDIR)/rtsrc/asn1CppEvtHndlr64.h \
    $(OSROOTDIR)/rtxersrc/rtSAXDefs.h \
    $(OSROOTDIR)/rtxsrc/OSRTStream.h \
    $(OSROOTDIR)/rtxsrc/OSRTCtxtHolder.h \
    $(OSROOTDIR)/rtxsrc/rtxPattern.h \
    $(OSROOTDIR)/rtxersrc/asn1XerCppTypes.h \
    $(OSROOTDIR)/rtxsrc/OSRTInputStream.h \
    $(OSROOTDIR)/rtxsrc/rtxStack.h \
    $(OSROOTDIR)/rtxsrc/rtxExternDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxCtype.h \
    $(OSROOTDIR)/rtxsrc/rtxCommonDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxXmlQName.h \
    $(OSROOTDIR)/rtxsrc/rtxUtil.h \
    $(OSROOTDIR)/rtxmlsrc/osrtxml.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxCppParserIF.h \
    $(OSROOTDIR)/rtsrc/ASN1TOctStr64.h \
    $(OSROOTDIR)/rtxsrc/rtxCharStr.h
	$(CCC) $(XERCFLAGS) -c -I$(OSROOTDIR) $(IPATHS_) $(XERSRCDIR)/asn1XerCppTypes.cpp

ASN1XERDecodeStream$(OBJ): \
    $(OSROOTDIR)/rtxsrc/rtxMemBuf.h \
    $(OSROOTDIR)/rtxsrc/rtxDList.h \
    $(OSROOTDIR)/rtxsrc/rtxFile.h \
    $(OSROOTDIR)/rtxsrc/rtxCommon.h \
    $(OSROOTDIR)/rtsrc/ASN1TOctStr.h \
    $(OSROOTDIR)/rtsrc/rtContext.h \
    $(OSROOTDIR)/rtxsrc/rtxReal.h \
    $(OSROOTDIR)/rtxersrc/asn1xer.h \
    $(OSROOTDIR)/rtxsrc/rtxBuffer.h \
    $(OSROOTDIR)/rtxsrc/rtxErrCodes.h \
    $(OSROOTDIR)/rtxsrc/OSRTMsgBuf.h \
    $(OSROOTDIR)/rtxsrc/rtxUtil.h \
    $(OSROOTDIR)/rtxsrc/rtxXmlQName.h \
    $(OSROOTDIR)/rtxsrc/rtxCharStr.h \
    $(OSROOTDIR)/rtsrc/ASN1TOctStr64.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxCppParserIF.h \
    $(OSROOTDIR)/rtxmlsrc/osrtxml.h \
    $(OSROOTDIR)/rtxsrc/rtxExternDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxStack.h \
    $(OSROOTDIR)/rtxsrc/rtxCommonDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxPattern.h \
    $(OSROOTDIR)/rtxersrc/asn1XerCppTypes.h \
    $(OSROOTDIR)/rtxsrc/OSRTCtxtHolder.h \
    $(OSROOTDIR)/rtsrc/asn1CppEvtHndlr64.h \
    $(OSROOTDIR)/rtxersrc/rtSAXDefs.h \
    $(OSROOTDIR)/rtxsrc/OSRTCtxtHolderIF.h \
    $(OSROOTDIR)/rtxsrc/rtxSList.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlErrCodes.h \
    $(OSROOTDIR)/rtsrc/rtExternDefs.h \
    $(OSROOTDIR)/rtsrc/asn1ErrCodes.h \
    $(OSROOTDIR)/rtxsrc/rtxBigInt.h \
    $(OSROOTDIR)/rtxsrc/osSysTypes.h \
    $(OSROOTDIR)/rtsrc/asn1type.h \
    $(OSROOTDIR)/rtxsrc/OSRTStreamIF.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxDefs.h \
    $(OSROOTDIR)/rtsrc/asn1CppTypes.h \
    $(OSROOTDIR)/rtxsrc/rtxDiag.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlNamespace.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxCppParser.h \
    $(OSROOTDIR)/rtxsrc/OSRTContext.h \
    $(OSROOTDIR)/rtxsrc/osMacros.h \
    $(OSROOTDIR)/rtsrc/ASN1Context.h \
    $(OSROOTDIR)/rtxsrc/rtxDateTime.h \
    $(OSROOTDIR)/rtxsrc/rtxContext.h \
    $(OSROOTDIR)/rtxsrc/rtxError.h \
    $(OSROOTDIR)/rtxsrc/rtxEnum.h \
    $(OSROOTDIR)/rtsrc/asn1CppEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/OSRTInputStreamIF.h \
    $(OSROOTDIR)/rtsrc/asn1tag.h \
    $(OSROOTDIR)/rtxsrc/rtxDynPtrArray.h \
    $(OSROOTDIR)/rtxsrc/rtxBitString.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlExternDefs.h \
    $(OSROOTDIR)/rtsrc/ASN1TObjId.h \
    $(XERSRCDIR)/ASN1XERDecodeStream.cpp \
    $(OSROOTDIR)/rtsrc/asn1CEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/rtxUTF8.h \
    $(OSROOTDIR)/rtxsrc/rtxMemory.h \
    $(OSROOTDIR)/rtxsrc/OSRTMsgBufIF.h \
    $(OSROOTDIR)/rtxersrc/ASN1XERDecodeStream.h
	$(CCC) $(XERCFLAGS) -c -I$(OSROOTDIR) $(IPATHS_) $(XERSRCDIR)/ASN1XERDecodeStream.cpp

ASN1XEREncodeStream$(OBJ): \
    $(OSROOTDIR)/rtxsrc/rtxPattern.h \
    $(OSROOTDIR)/rtxersrc/asn1XerCppTypes.h \
    $(OSROOTDIR)/rtxsrc/OSRTCtxtHolder.h \
    $(OSROOTDIR)/rtxersrc/rtSAXDefs.h \
    $(OSROOTDIR)/rtsrc/asn1CppEvtHndlr64.h \
    $(OSROOTDIR)/rtxsrc/rtxSList.h \
    $(OSROOTDIR)/rtxsrc/OSRTCtxtHolderIF.h \
    $(OSROOTDIR)/rtsrc/ASN1TOctStr64.h \
    $(OSROOTDIR)/rtxsrc/rtxCharStr.h \
    $(OSROOTDIR)/rtxmlsrc/osrtxml.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxCppParserIF.h \
    $(OSROOTDIR)/rtxsrc/rtxUtil.h \
    $(OSROOTDIR)/rtxsrc/rtxXmlQName.h \
    $(OSROOTDIR)/rtxsrc/rtxCommonDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxExternDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxStack.h \
    $(OSROOTDIR)/rtsrc/rtContext.h \
    $(OSROOTDIR)/rtxsrc/rtxErrCodes.h \
    $(OSROOTDIR)/rtxsrc/OSRTMsgBuf.h \
    $(OSROOTDIR)/rtxsrc/rtxReal.h \
    $(OSROOTDIR)/rtxersrc/asn1xer.h \
    $(OSROOTDIR)/rtxsrc/rtxBuffer.h \
    $(OSROOTDIR)/rtxsrc/rtxFile.h \
    $(OSROOTDIR)/rtxsrc/rtxDList.h \
    $(OSROOTDIR)/rtxsrc/rtxMemBuf.h \
    $(OSROOTDIR)/rtxsrc/rtxCommon.h \
    $(OSROOTDIR)/rtsrc/ASN1TOctStr.h \
    $(OSROOTDIR)/rtsrc/asn1CEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/rtxUTF8.h \
    $(OSROOTDIR)/rtxsrc/rtxBitString.h \
    $(OSROOTDIR)/rtsrc/ASN1TObjId.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlExternDefs.h \
    $(OSROOTDIR)/rtxsrc/OSRTMsgBufIF.h \
    $(OSROOTDIR)/rtxsrc/rtxMemory.h \
    $(OSROOTDIR)/rtsrc/asn1CppEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/rtxError.h \
    $(OSROOTDIR)/rtxsrc/rtxEnum.h \
    $(OSROOTDIR)/rtxsrc/rtxDynPtrArray.h \
    $(OSROOTDIR)/rtxsrc/OSRTInputStreamIF.h \
    $(OSROOTDIR)/rtsrc/asn1tag.h \
    $(OSROOTDIR)/rtxsrc/rtxDiag.h \
    $(OSROOTDIR)/rtsrc/asn1CppTypes.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxDefs.h \
    $(OSROOTDIR)/rtxersrc/ASN1XEREncodeStream.h \
    $(OSROOTDIR)/rtsrc/ASN1Context.h \
    $(OSROOTDIR)/rtxsrc/rtxDateTime.h \
    $(XERSRCDIR)/ASN1XEREncodeStream.cpp \
    $(OSROOTDIR)/rtxsrc/OSRTOutputStreamIF.h \
    $(OSROOTDIR)/rtxsrc/rtxContext.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlNamespace.h \
    $(OSROOTDIR)/rtxmlsrc/rtSaxCppParser.h \
    $(OSROOTDIR)/rtxsrc/osMacros.h \
    $(OSROOTDIR)/rtxsrc/OSRTContext.h \
    $(OSROOTDIR)/rtsrc/asn1ErrCodes.h \
    $(OSROOTDIR)/rtxmlsrc/rtXmlErrCodes.h \
    $(OSROOTDIR)/rtsrc/rtExternDefs.h \
    $(OSROOTDIR)/rtxsrc/OSRTStreamIF.h \
    $(OSROOTDIR)/rtsrc/asn1type.h \
    $(OSROOTDIR)/rtxsrc/rtxBigInt.h \
    $(OSROOTDIR)/rtxsrc/osSysTypes.h
	$(CCC) $(XERCFLAGS) -c -I$(OSROOTDIR) $(IPATHS_) $(XERSRCDIR)/ASN1XEREncodeStream.cpp

ASN1XERString$(OBJ): \
    $(OSROOTDIR)/rtsrc/rtExternDefs.h \
    $(OSROOTDIR)/rtsrc/asn1ErrCodes.h \
    $(OSROOTDIR)/rtxsrc/osSysTypes.h \
    $(OSROOTDIR)/rtsrc/asn1type.h \
    $(OSROOTDIR)/rtxsrc/osMacros.h \
    $(OSROOTDIR)/rtxsrc/rtxContext.h \
    $(OSROOTDIR)/rtxsrc/rtxError.h \
    $(XERSRCDIR)/ASN1XERString.h \
    $(OSROOTDIR)/rtsrc/asn1tag.h \
    $(OSROOTDIR)/rtxsrc/rtxBitString.h \
    $(OSROOTDIR)/rtsrc/asn1CEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/rtxUTF8.h \
    $(OSROOTDIR)/rtxsrc/rtxMemory.h \
    $(OSROOTDIR)/rtxsrc/rtxMemBuf.h \
    $(OSROOTDIR)/rtxsrc/rtxDList.h \
    $(OSROOTDIR)/rtsrc/rtContext.h \
    $(OSROOTDIR)/rtxersrc/asn1xer.h \
    $(OSROOTDIR)/rtxsrc/rtxErrCodes.h \
    $(XERSRCDIR)/ASN1XERString.cpp \
    $(OSROOTDIR)/rtxsrc/rtxExternDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxStack.h \
    $(OSROOTDIR)/rtxsrc/rtxCommonDefs.h \
    $(OSROOTDIR)/rtxersrc/rtSAXDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxSList.h
	$(CCC) $(XERCFLAGS) -c -I$(OSROOTDIR) $(IPATHS_) $(XERSRCDIR)/ASN1XERString.cpp

saxParser$(OBJ): \
    $(OSROOTDIR)/rtxsrc/rtxMemory.h \
    $(OSROOTDIR)/rtxsrc/rtxUTF8.h \
    $(OSROOTDIR)/rtsrc/asn1CEvtHndlr.h \
    $(OSROOTDIR)/rtxsrc/rtxBitString.h \
    $(OSROOTDIR)/rtsrc/asn1tag.h \
    $(XERSRCDIR)/ASN1XERString.h \
    $(OSROOTDIR)/rtxsrc/rtxError.h \
    $(OSROOTDIR)/rtxsrc/rtxContext.h \
    $(OSROOTDIR)/rtxsrc/osMacros.h \
    $(OSROOTDIR)/rtsrc/asn1type.h \
    $(XERSRCDIR)/saxParser.h \
    $(OSROOTDIR)/rtxsrc/osSysTypes.h \
    $(OSROOTDIR)/rtsrc/rtExternDefs.h \
    $(OSROOTDIR)/rtsrc/asn1ErrCodes.h \
    $(OSROOTDIR)/rtxsrc/rtxSList.h \
    $(OSROOTDIR)/rtxersrc/rtSAXDefs.h \
    $(XERSRCDIR)/saxParser.cpp \
    $(OSROOTDIR)/rtxsrc/rtxCommonDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxStack.h \
    $(OSROOTDIR)/rtxsrc/rtxExternDefs.h \
    $(OSROOTDIR)/rtxsrc/rtxErrCodes.h \
    $(OSROOTDIR)/rtxersrc/asn1xer.h \
    $(OSROOTDIR)/rtsrc/rtContext.h \
    $(OSROOTDIR)/rtxsrc/rtxDList.h \
    $(OSROOTDIR)/rtxsrc/rtxMemBuf.h
	$(CCC) $(XERCFLAGS) -c -I$(OSROOTDIR) $(IPATHS_) $(XERSRCDIR)/saxParser.cpp

