XER_C_COMMON_RTOBJECTS = \
   xerCmpText$(OBJ) \
   xerContext$(OBJ) \
   xerCopyText$(OBJ) \
   xerDecBMPStr$(OBJ) \
   xerDecBase64Str$(OBJ) \
   xerDecBase64StrValue$(OBJ) \
   xerDecBigInt$(OBJ) \
   xerDecBinStrValue$(OBJ) \
   xerDecBitStr$(OBJ) \
   xerDecBitStrMemBuf$(OBJ) \
   xerDecBool$(OBJ) \
   xerDecCopyBitStr$(OBJ) \
   xerDecCopyDynBitStr$(OBJ) \
   xerDecCopyDynOctStr$(OBJ) \
   xerDecCopyOctStr$(OBJ) \
   xerDecDynAscCharStr$(OBJ) \
   xerDecDynBase64Str$(OBJ) \
   xerDecDynBitStr$(OBJ) \
   xerDecDynOctStr$(OBJ) \
   xerDecDynUTF8Str$(OBJ) \
   xerDecHexStrValue$(OBJ) \
   xerDecInt$(OBJ) \
   xerDecInt64$(OBJ) \
   xerDecObjId$(OBJ) \
   xerDecObjId64$(OBJ) \
   xerDecOctStr$(OBJ) \
   xerDecOctStrMemBuf$(OBJ) \
   xerDecOpenType$(OBJ) \
   xerDecReal$(OBJ) \
   xerDecReal10$(OBJ) \
   xerDecRelativeOID$(OBJ) \
   xerDecUInt$(OBJ) \
   xerDecUInt64$(OBJ) \
   xerDecUnivStr$(OBJ) \
   xerEncAscCharStr$(OBJ) \
   xerEncBMPStr$(OBJ) \
   xerEncBase64Str$(OBJ) \
   xerEncBigInt$(OBJ) \
   xerEncBinStrValue$(OBJ) \
   xerEncBitStr$(OBJ) \
   xerEncBool$(OBJ) \
   xerEncChar$(OBJ) \
   xerEncEmptyElement$(OBJ) \
   xerEncEndDocument$(OBJ) \
   xerEncEndElement$(OBJ) \
   xerEncHexStrValue$(OBJ) \
   xerEncIndent$(OBJ) \
   xerEncInt$(OBJ) \
   xerEncInt64$(OBJ) \
   xerEncNamedValue$(OBJ) \
   xerEncNewLine$(OBJ) \
   xerEncNull$(OBJ) \
   xerEncObjId$(OBJ) \
   xerEncObjId64$(OBJ) \
   xerEncOctStr$(OBJ) \
   xerEncOpenType$(OBJ) \
   xerEncOpenTypeExt$(OBJ) \
   xerEncReal$(OBJ) \
   xerEncReal10$(OBJ) \
   xerEncRelativeOID$(OBJ) \
   xerEncStartDocument$(OBJ) \
   xerEncStartElement$(OBJ) \
   xerEncUInt$(OBJ) \
   xerEncUInt64$(OBJ) \
   xerEncUniCharData$(OBJ) \
   xerEncUniCharStr$(OBJ) \
   xerEncUnivStr$(OBJ) \
   xerEncXmlCharStr$(OBJ) \
   xerFinalizeMemBuf$(OBJ) \
   xerGetElemIdx$(OBJ) \
	xerGetLibInfo$(OBJ) \
   xerGetMsgPtrLen$(OBJ) \
   xerGetSeqElemIdx$(OBJ) \
   xerPutCharStr$(OBJ) \
   xerSetDecBufPtr$(OBJ) \
   xerSetEncBufPtr$(OBJ) \
   xerTextLength$(OBJ) \
   xerTextToCStr$(OBJ)

XER_C_RTOBJECTS = \
   $(XER_C_COMMON_RTOBJECTS) \
   ASN1SAX_XEROpenType$(OBJ)

XER_CPP_RTOBJECTS = \
   $(XER_C_COMMON_RTOBJECTS) \
   ASN1CXerOpenType$(OBJ) \
   ASN1XERDecodeStream$(OBJ) \
   ASN1XEREncodeStream$(OBJ) \
   ASN1XERString$(OBJ) \
   asn1XerCppTypes$(OBJ)
